### PR TITLE
Make sound of piston explosions toggleable

### PR DESCRIPTION
**Pull request by FrankHeijden**

### CODE REVIEW

**Comment by RoboMWM** [comment]
Mind adding a blurb here that I can paste into the documentation?

(I'm working on a docs repo so that this can be done directly in the future.)

**Comment by FrankHeijden** [comment]
> Mind adding a blurb here that I can paste into the documentation?
> 
> (I'm working on a docs repo so that this can be done directly in the future.)

This option disables the explosion sound when GriefPrevention removes pistons, for example when pistons aren’t allowed to move blocks into claims.

**Comment by FrankHeijden** [comment]
Does this mean it will get merged when 10.15 is getting released (when will that happen?)

**Comment by Jikoo** [comment]
> Does this mean it will get merged when 10.15 is getting released (when will that happen?)

Hopefully before, I assume I'll have to rebase #933 after this is pulled. As far as 16.15, all of the issues assigned to the milestone are now closed, but some are still open for 16.14. https://github.com/TechFortress/GriefPrevention/milestones

**Comment by RoboMWM** [comment]
I'm moving all features (particularly those that require documentation) to 16.15. Already more than enough changes for a patch release.

**Comment by FrankHeijden** [comment]
Any news on 16.15? 😄

**Comment by FrankHeijden** [comment]
I see 16.15 has just been released, but the milestone for 16.15's release has not been completed yet (e.g. this PR isn't merged, although its labelled for 16.15's release?)

**Comment by RoboMWM** [comment]
Forgot to update milestone. See release notes for reason why it was released as 16.15.

**Comment by RoboMWM** [comment]
yup, figured this would conflict the moment I pulled the pistons PR. If you wouldn't mind resolving please?

**Comment by Jikoo** [comment]
Pinging @FrankHeijden in case you forgot this PR since I know you're active

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
