### PR TITLE
Fix pistons in subclaims

### PR DESCRIPTION
**Pull request by FrankHeijden**
Pistons which are trying to push a block in pistons will not get fired:

This PR fixes the issue.

### CODE REVIEW

**Comment by Jikoo** [comment]
Oh gross, forgot that subclaims don't set owner ID. May be better to add a method `Claim#getOwnerID` to pair with `Claim#getOwnerName`, then use that here. There are several uses in pistons that probably need the fix, not just `EVERYWHERE_SIMPLE`.

**Comment by Jikoo** [comment]
Also thank you for this, I know I missed that in my ClaimPermissionEvent PR too.

**Review by Jikoo — APPROVED** [review]
Looks good to me 👍

**Comment by FrankHeijden** [comment]
I noticed more issues with the new Piston checks. This is best reproducible when there are many claims in the area; the boundary checks are off. Some parts of the claim allow pushing, some parts do not. I think the bounding box checks may be a bit overcomplicated regarding that matter. I think it's just best to get the claim(s) of the pushed block and the piston and compare these two, not doing any boundingbox checks.

**Comment by Jikoo** [comment]
You're probably seeing the absence of #1036, would make sure you pull that patch onto whatever build you're testing with.

**Comment by Jikoo** [comment]
Also yes, the bounding box is not perfect, it's just the maximum affected zone. If you look at [the writeup](https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#pistonmovement) for EVERYWHERE_SIMPLE you'll see an image I included highlighting the shortcomings - the claim does not interfere with the piston and blocks, but retraction is blocked because the bounding box conflicts. If you want exact mode, EVERYWHERE exists for that reason.

**Comment by FrankHeijden** [comment]
> Also yes, the bounding box is not perfect, it's just the maximum affected zone. If you look at [the writeup](https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#pistonmovement) for EVERYWHERE_SIMPLE you'll see an image I included highlighting the shortcomings - the claim does not interfere with the piston and blocks, but retraction is blocked because the bounding box conflicts. If you want exact mode, EVERYWHERE exists for that reason.

No I mean, when you have a claim solely in certain parts of your claim, it wont extend at all. not even on the boundary. I will be using the "EVERYWHERE" setting from now on.

**Comment by Jikoo** [comment]
> No I mean, when you have a claim solely in certain parts of your claim, it wont extend at all. not even on the boundary. I will be using the "EVERYWHERE" setting from now on.

Could you attach a screenshot of a setup like that, ideally with F3 up? If there is a problem I'm perfectly happy to dive into it myself, but I haven't been hearing about that in the limited live testing I've been running.

**Comment by FrankHeijden** [comment]
Im not able to reproduce on my testserver unfortunately, in a hugely dense claiming area (e.g. a town) this behaviour pops up inconsistently though, some parts of a non-sub claim do work as intended, and some do not.

**Comment by RoboMWM** [comment]
ya, a getter is cool for Claim, I get it, Claim is bad, but at the same time I kinda don't want people to start using this just cuz it exists now when Claim may change again. Idk. whatever.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
