### PR TITLE
Static methods should not be accessed via reference

### PR DESCRIPTION
**Pull request by Jikoo**
Last one for today, I promise.

### CODE REVIEW

**Comment by RoboMWM** [comment]
I prefer instance and would like to remove "static" from a few of these, though idk what the convention is these days.

**Comment by Jikoo** [comment]
Yeah, this was more of a "it would be nice to see this file as something other than a mass of warnings without just turning off what is generally a reasonable inspection" than an actual design choice. The method is currently static and is used in a total of 169 places across all various signatures. 97 usages (the ones changed by this PR) were used in a non-static context, and I'm sure more could easily be changed.

I'd generally prefer a non-static approach, but it's logging. Debug logging often happens in the areas that are harder to reach, so I'm not opposed to static as much as I normally would be. As easy as constructor dependency injection is, you have to draw the line somewhere.

The only thing I really care about regarding this method is that we please make it lower camel case if the signature is changed, naming conventions are something I definitely get pedantic about.

**Comment by RoboMWM** [comment]
I'm pretty sure BigScary came from a C# background, which the convention there is paschal case for methods and variables - which also explains the public fields.

**Review by RoboMWM — APPROVED** [review]
I specifically passed in the instance here and undid the static use, but oh well, guess I'll let legacy remain consistent.

**Pull request merged**
