### PR TITLE
Remove explicit type declaration

### PR DESCRIPTION
**Pull request by Jikoo**
Going to try to chip away at the hundreds of compiler warnings in GP when I have time.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Meh. I happen to kinda prefer verbosity but whatever.

**Review by RoboMWM — APPROVED** [review]

**Comment by RoboMWM** [comment]
btw if you have free time I'm also trying to figure out a good GitHub pages/Jekyll theme that uses no/minimal javascript and is responsive (works well on mobile and desktop) or just a good way to organize documentation for the https://github.com/TechFortress/GriefPrevention-Docs repo (which is where the domain points to now).

**Comment by Jikoo** [comment]
Hm, I'll keep my eyes out. Unfortunately websites are not my area of expertise, I only do frontend work once in a blue moon.

**Comment by RoboMWM** [comment]
Same lol, I'm just looking for something simple that has search, or at least can auto-generate a TOC of some sorts.

**Pull request merged**
