### PR TITLE
Add several hostile non-monsters

### LINKED ISSUE #885: Players can't kill Hoglins in claims
### What happened:
Players can't kill hogslins in another persons claim.
image

### What was expected:
Hoglins are considered to be aggressive mobs, and therefor shouldn't be protected by claims?

### Steps to reproduce:
1. Make a claim in the nether
2. Spawn a hoglin
3. Try to attack it on another account

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Paper version git-Paper-89 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`:  GriefPrevention version 16.14.0

### PR DESCRIPTION
**Pull request by Jikoo**
I split this into two commits. The first is what GP already does, so if that's the desired behavior, that can be cherry picked out and the second can be ignored. Both add support for slimes (which for some reason were missed even though magma cubes were included), aggressive pandas, and hoglins.

The second commit adds specific protections for entities that are non-threatening.
* Size 0 slimes deal 0 damage no matter the difficulty
* Polar bears only enrage when players are too close to cubs or if attacked.
* Hoglins [can be pacified](https://minecraft.gamepedia.com/Hoglin#Farming) by the presence of certain blocks.

This may be a little inconvenient in some cases (it's way easier to just potshot an entity before it sees you) but it would allow players to set up breeding farms or zoos more easily.
My only reservation about the second approach is that I believe it could be bypassed by luring - the player would be targeted, just not in a hostile manner - so it might lull players into a false sense of security. I don't think there's a way to check with the API whether the mob is targeting a player because it's lured or hostile specifically.

Closes #885

### CODE REVIEW

**Comment by Jikoo** [comment]
Looked into this more, it is in fact possible to detect lures. Will update PR shortly.

**Comment by Jikoo** [comment]
@RoboMWM How do you feel about using NBT tags instead of metadata? NBT persists with GP uninstallation and persistence isn't really required for target reason tracking, but metadata leaks (minorly) and GP doesn't clean it up. GP does currently use metadata for tracking purposes, but I believe that's mostly due to the age of the code.

I'm going to proceed with NBT for now, but I'm perfectly willing to change that if you want GP to stick to metadata.

**Comment by Jikoo** [comment]
Not super happy about the addition of the EntityTargetLivingEntityEvent, I believe that fires a lot, but the return conditions should keep our usage pretty efficient. I did note in my search to see if it's in use that GP claims to prevent luring animals, but does not actually. I don't think it's something we should add - players can and should be encouraged to build pens to expect to keep their animals - but it may be a good idea to remove that from the entry in the [features](https://github.com/TechFortress/GriefPrevention/wiki/Features).
>* No killing or luring animals away.

**Comment by RoboMWM** [comment]
I feel like the extra features for mobs that can become neutral, at the very least, feel like extra features/gameplay changes. E.g., players have encased mobs such as polar bears in glass structures. Wondering if these should be a config or not...

As for luring, I'm not sure when Big_Scary implemented that - highly likely before luring was a thing, as he only is protecting against jump potion and some other thing I can't recall. I'm guessing that as long as they're penned in, they can't be lured out without things that modify their movement like potions. Probably does need to be dropped though since I don't recall any complaints about this.

**Comment by Jikoo** [comment]
I mean, luring is really only possible if a mob can wander out on its own or be pushed anyway, so I definitely don't think it's a thing GP needs to be concerned with.

Like I said, if we don't want GP to ever protect edge cases, f3e6059 can be cherry picked and that's the end of it. That said, we get a decent number of zoo-style requests, so I figure it may be easier to just add the full zoo friendliness feature while we're here. Speaking of, this would also close #553

**Comment by RoboMWM** [comment]
Only other thing I can think of against for protecting neutral/provokable mobs is that players can assume these mobs are classified as "animals" and wouldn't think they can defend themselves. Other than that I guess I could pull.

**Comment by RoboMWM** [comment]
I've been debating this internally every time I look at this but I guess it doesn't alter the design much, just the implementation.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
