### PR TITLE
ConfigOption - FireSpread in claims

### PR DESCRIPTION
**Pull request by ShaneBeee**
**Related to issue:** #428 

Added 2 config options to allow fire to spread and do damage in claims (default = false)

Tested, works like a charm :)

### CODE REVIEW

**Review by RoboMWM — APPROVED** [review]
Eh

**Comment by TomLewis** [comment]
Request was for players to toggle it with a command, like toggle explosions.

**Comment by ShaneBeee** [comment]
> Request was for players to toggle it with a command, like toggle explosions.

Umm... NO! I wrote the request for there to be a config option, not a toggle... this PR was done to solve the issue #428 I created not another issue.

**Comment by TomLewis** [comment]
Eh, useless.

**Comment by RoboMWM** [comment]
I haven't checked out this branch myself but appveyor is reporting that the author of the commit is BuildTools… Mind rebasing and fixing the author name (or verify that it is correct)?

Do `git log` to check.

**Comment by ShaneBeee** [comment]
The only reason I could think it would show BuildTools is because I commit and push from IntelliJ.... in my commits it shows my name, so that is really odd to you its showing BuildTools

**Comment by ShaneBeee** [comment]
This is what git log shows
```
commit 50afa9bcafc43eac33d0f17b8b13ae3daa05c2a0 (HEAD -> master, origin/master, origin/HEAD)
Author: BuildTools <shanebolenback@me.com>
Date:   Fri Nov 30 13:29:04 2018 -0800

    ConfigOption - FireSpread in claims

commit cf0a60ea3bfc460badd60c957e2ed6326c619fd5
Author: BuildTools <shanebolenback@me.com>
Date:   Fri Nov 30 13:27:00 2018 -0800

    ConfigOption - FireSpread in claims

```

**Comment by RoboMWM** [comment]
Well, that confirms you need to fix the commit author in git, lol.

**Comment by ShaneBeee** [comment]
Haha yes I see that now. I have changed it.
I dont know how to push a commit though when theres no changes

**Comment by RoboMWM** [comment]
You fix them via rebasing. You will be modifying this PR's commit history to fix.

**Comment by RoboMWM** [comment]
No, you rebase, not add more commits... no idea what you did :s

**Comment by ShaneBeee** [comment]
Yeah this thing confuses me.... when i hover over rebase i see two options.

Do I click mine or yours?

**Comment by RoboMWM** [comment]
Uh... what you have to do will involve the command line.

Basically look online on how to change commit author, as I don't recall.

Use `git rebase -i (your first commit hash here)` to enter interactive rebase where you can pick out the commits to edit (and to remove in this case). I'm guessing you'll have to `pick` the commits to edit, then edit the commit author for each as they're displayed to you.

You will have to force push `git push -f` when you're done, so if you're able to push without forcing, then you know you haven't fixed it yet.

**Comment by ShaneBeee** [comment]
Yeah so the terminal way of doing it in IntelliJ just wasn't working for me, but apparently, it has a built-in way to do it but I have messed something up along the way and now the option for it won't show up. I think at this point I'm better off closing this pull request and just doing a new one

**Pull request closed without merging**
