### PR TITLE
Deny brushing of suspicious blocks in claims without build trust

### LINKED ISSUE #2064: Suspicious Sand and Gravel not protected from brushing mechanic
### Observed Behavior

You can brush suspicious sand/gravel in claims without trust.

https://minecraft.fandom.com/wiki/Suspicious_Block#Brushing

### Expected Behavior

Claims should stop untrusted players from brushing suspicious sand/gravel.

### Reproduction steps

1. Make claim around suspicious sand block
2. be person without trust
3. Brush the sand
4. It breaks

### Stack trace or error log

_No response_

### Server version

```shell
This server is running Paper version git-Paper-22 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f7b386d)
```

### GriefPrevention version

```shell
version .18.1-31-gf6b9bdf
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Survival
      world: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: false
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1024
    Claim Blocks Accrued Per Hour:
      Default: 256
    Max Accrued Claim Blocks:
      Default: 10000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 7
    MinimumWidth: 4
    MinimumArea: 25
    MaximumDepth: -63
    InvestigationTool: GOLDEN_AXE
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 180
      UnusedClaimDays: 180
      AllClaims:
        DaysInactive: 730
        ExceptWhenOwnerHasTotalClaimBlocks: 4096
        ExceptWhenOwnerHasBonusClaimBlocks: 4096
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: true
    MaximumNumberOfClaimsPerPlayer: 200
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: true
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 4
    LoginLogoutNotificationsPerMinute: 10
    ChatSlashCommands: /me;/global;/local;/afk
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  This will be removed once you
      rank up..
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 90
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/spec
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: IGNORED
  PistonExplosionSound: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 4
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 30
    OfflinePlayer_cache_days: 1825
  Abridged Logs:
    Days To Keep: 30
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

_No response_

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

### PR DESCRIPTION
**Pull request by RoboMWM**
Closes #2064

### CODE REVIEW

**Comment by RoboMWM** [comment]
Ideally I'd like to make branches in my own repository, but Github Desktop's UI only allows me to branch off of the top-most repo, even if mine is a fork of a fork... I'll eventually learn how to do it via cli commands

**Comment by Jikoo** [comment]
Personally for simple git stuff I just use the UI built into my IDE these days - the one in Eclipse worked fine when I used it, and IntelliJ's is pretty nice too. GitHub Desktop doesn't seem to have any concept of heads that are not "origin," and as a result I only use it for pushing to the one GH org that for some unknown reason rejects my key (even though the same key works for everything else I can access).
Only thing I do seem to end up doing regularly via cli is managing tags, because no, I do not want to push every tag made ever so my most recent tag will show up, thank you very much for offering, built in UI. I guess the other "major" hitter is that every once in a while I'll get a little too crazy with a rebase and have to manually fix it.

**Comment by RoboMWM** [comment]
Maybe git integration with IDEs has improved, but I just like having something very nice and colorful to show my diffs without the other IDE stuff in the way IMO. I'll prolly try to give it another go, but it's also, in a way, looking at the diff with "a fresh set of eyes" cuz I'm not using my editor I just stared at for an hour.

Anyways I may change to BrushableBlock instead of a switch. Guess that'll make it more future-proof too.

**Comment by RoboMWM** [comment]
This does not work. PlayerInteractEvent is only fired once as long as the player is looking at a block and has not let go of right-click nor has looked away from a block (i.e. targeting air). Thus, the player can look at contigously-connected blocks and brush any block he chooses, and bukkit's events have absolutely no idea what's happening, since no event is fired when a suspicious block has been fully brushed.

**Comment by Jikoo** [comment]
Sounds like we'd have to do PlayerAnimationEvent, assuming the arm swings for the brush. Kinda rough though, there really should be some other event for this.

**Comment by QarthO** [comment]
> Sounds like we'd have to do PlayerAnimationEvent, assuming the arm swings for the brush. Kinda rough though, there really should be some other event for this.

Even though the player arm is visually swinging with the brush in hand, the PlayerAnimationEvent is not being fired.
Double checked and no event that is fired apart from the initial PlayerInteractEvent.

I do have a small work around, to tackle this problem. I tested it myself and it looks like it works

```java
public void onPlayerInteractEvent(PlayerInteractEvent event){
    // ... initial null checks
    // ... put checks to make sure they aren't trying to open an inventory or
    //    interact with another block and they just happen to be holding a brush
       
    if(materialInHand == Material.BRUSH){
        if (!(clickedBlock.getState() instanceof BrushableBlock))
            event.setCancelled(true);
    }
}
```
You are able to cancel the initial PlayerInteractEvent , which prevents the user from moving to a brushable block.
We'd just need to make sure to not cancel the event if they're trying to open a chest or something like that while holding a brush.

**Comment by QarthO** [comment]
> > Sounds like we'd have to do PlayerAnimationEvent, assuming the arm swings for the brush. Kinda rough though, there really should be some other event for this.
> 
> Even though the player arm is visually swinging with the brush in hand, the PlayerAnimationEvent is not being fired. Double checked and no event that is fired apart from the initial PlayerInteractEvent.
> 
> I do have a small work around, to tackle this problem. I tested it myself and it looks like it works
> 
> ```java
> public void onPlayerInteractEvent(PlayerInteractEvent event){
>     // ... initial null checks
>     // ... put checks to make sure they aren't trying to open an inventory or
>     //    interact with another block and they just happen to be holding a brush
>        
>     if(materialInHand == Material.BRUSH){
>         if (!(clickedBlock.getState() instanceof BrushableBlock))
>             event.setCancelled(true);
>     }
> }
> ```
> 
> You are able to cancel the initial PlayerInteractEvent , which prevents the user from moving to a brushable block. We'd just need to make sure to not cancel the event if they're trying to open a chest or something like that while holding a brush.

Actually, technically this won't work. A player could place a suspicious block outside of a claim. Begin brushing it, (since it's outside of a claim we wouldn't want to cancel it) then all while never letting go of right click, move inside the claim and brush "protected" suspicious blocks.

Guess the only answer here is to wait until Spigot correctly handles this event. Or hopefully actually implement proper PlayerBrushEvents

**Comment by QarthO** [comment]
Went ahead and created the issue letting spigot know. tbh, hopefully they just add actual PlayerBrushEvents

https://hub.spigotmc.org/jira/browse/SPIGOT-7501

**Pull request closed without merging**
