### PR TITLE
Fix piston changes causing NPE in admin claims

### PR DESCRIPTION
**Pull request by Jikoo**
Addresses https://github.com/TechFortress/GriefPrevention/pull/933#issuecomment-692398443

### CODE REVIEW

**Comment by RoboMWM** [comment]
Uh, do we want to do Objects#equals? Pretty sure UUID implements equals.

Anyways I was refactoring this so it isn't a complex statement.

**Comment by Jikoo** [comment]
`Objects#equals`:
```Java
public static boolean equals(Object a, Object b) {
    return (a == b) || (a != null && a.equals(b));
}
```

**Comment by Jikoo** [comment]
If you want to refactor in another way that's fine though, this was just the simplest fix for the way I'd implemented it.

**Comment by RoboMWM** [comment]
Unless I'm remembering inheritance incorrectly, I'd assume that uses the parent Object#equals.

**Comment by RoboMWM** [comment]
k I'm wrong

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
