### PR TITLE
Added gitlab CI

### PR DESCRIPTION
**Pull request by NgLoader**
You only need to push a new tag to release a version

1. git checkout ``release branch``
2. git tag ``version``
3. git push origin ``version``

### CODE REVIEW

**Comment by RoboMWM** [comment]
This is interesting, does it work if I tag on github (e.g. create a release)?

Although I usually like to remove the commit hash locally before releasing (though I forgot to do so for 16.12.0), and I prefer to link to bukkitdev anyways for releases (so less people miss the changelog) unless you can find out how to automate uploading there.

**Comment by NgLoader** [comment]
You need to commit a tag
when you create a release it will fail (thanks to github for that)

**Comment by NgLoader** [comment]
Here is a project where I use it [Orebfuscator Releases](https://github.com/TeamWuffy/Orebfuscator/releases)

**Comment by NgLoader** [comment]
I commit some changes to make it happen tomorrow 💻

**Comment by RoboMWM** [comment]
gonna work with release drafter

**Pull request closed without merging**
