### PR TITLE
Fix wrapper for WG/WE 7.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by mirolm**
This should fix the crashes with WorldGuard. The request adds the newest WG/WE 7.0.0-SNAPSHOT. 

Keep in mind sk89q repo have some issue in bukkit section and fails to download bukkit 1.6.2-R0.1 with error 500. To workaround this download a copy of the jar and add it locally with:

http://maven.sk89q.com/repo/org/bukkit/bukkit/1.6.2-R0.1-SNAPSHOT/

mvn install:install-file -Dfile=bukkit-1.6.2-R0.1-20130804.014923-14.jar -DgroupId=org.bukkit -DartifactId=bukkit -Dversion=1.6.2-R0.1-SNAPSHOT -Dpackaging=jar -DgeneratePom=true

Please test if it works as expected.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Have you reported this maven issue with WorldGuard/WorldEdit? Would be nice to not have CI builds fail because of this.

**Comment by mirolm** [comment]
I have reported the issue in their irc channel and forum, but i do not know if it will be fixed.

Essentials repo has the same bukkit jar - this will fix the build.

        <repository>
            <id>ess-repo</id>
            <url>http://repo.ess3.net/content/groups/public/</url>
        </repository>

**Comment by RoboMWM** [comment]
If that's what WorldGuard needs to build itself/retrieve the dependency, then go ahead and add that maven repo for now.

**Comment by mirolm** [comment]
Actually it does not fix it. We have to wait for sk89q to fix his repo.

**Pull request closed without merging**
