### PR TITLE
Do a build permission check on sign change

### LINKED ISSUE #950: GriefPrevention does not prevent signs from being edited in forbidden claims
### What happened:
`me.ryanhamshire.GriefPrevention.BlockEventHandler#onSignChanged()` does not cancel its `SignChangeEvent` when a player modifies a sign inside a claim where they do not have access to build:

image
image

### What was expected:
`me.ryanhamshire.GriefPrevention.BlockEventHandler#onSignChanged()` sets its `SignChangeEvent` to canceled when a player modifies a sign inside a claim where they do not have access to build.

image

### Steps to reproduce:
1. Install the [SignEdit for Bukkit](https://git.io/SignEdit) plugin
2. Create an admin claim.
3. Place a sign inside this claim.
4. As a player that has the `signedit.sign.*` permission but no build permissions in the admin claim, run `/sign set 1 Grief test` while looking at the sign.

### Server and GriefPrevention version:
Paste of `/version`: 
```
[17:10:50] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9639cf7-8fb6585 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[17:10:50] [Server thread/INFO]: You are running the latest version
```
Paste of `/version GriefPrevention`: 
```
[17:11:29 INFO]: GriefPrevention version 16.14.0
```

### Stack trace/error or server log

_Not applicable_

### GriefPrevention config.yml

_Not applicable_

### Plugin list (if applicable):

- [GriefPrevention](https://github.com/TechFortress/GriefPrevention/) v16.14.0
- [SignEdit for Bukkit](https://git.io/SignEdit) v1.12.1

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

### Additional context

It is not possible to edit a sign in vanilla Minecraft as of version 1.16.2, but [Mojang are looking into adding the functionality](https://web.archive.org/web/20200715010911if_/https://bugs.mojang.com/browse/MC-192263?focusedCommentId=763948&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-763948).  I think it is important to be proactive and fix this bug to prevent sign text griefing, even in the absence of another plugin that modifies sign text.

### PR DESCRIPTION
**Pull request by Deltik**
Fixes: #950

### CODE REVIEW

**Comment by RoboMWM** [comment]
Only way I can see this happening is if you place a sign, then someone claims the land while you're typing up the text...?

**Comment by Jikoo** [comment]
I assume it's for compatibility with a sign editing plugin that doesn't fire any standard building events. Really, the sign editing plugin should fire a BlockPlaceEvent for the sign as a catch-all, but it would be good for GP to also check this.

**Comment by Deltik** [comment]
> I assume it's for compatibility with a sign editing plugin that doesn't fire any standard building events. Really, the sign editing plugin should fire a BlockPlaceEvent for the sign as a catch-all, but it would be good for GP to also check this.

@Jikoo: I looked into the other events, particularly [`BlockBreakEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockBreakEvent.html) and [`BlockPlaceEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockPlaceEvent.html) as if the sign were broken and replaced, but they do not make sense in the context of the documented behavior in the Bukkit API.  In the API docs, [`SignChangeEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/SignChangeEvent.html) is described as "Called when a sign is changed by a player."  [SignEdit for Bukkit fires this event as documented.](https://github.com/Deltik/SignEdit/blob/fde4032f248145910be266b914978fffe495daf5/src/org/deltik/mc/signedit/SignText.java#L100)

`BlockBreakEvent` could be called, but the sign block never actually breaks during the sign edit operation, and `BlockPlaceEvent` also doesn't make sense because the sign isn't placed again.

Yes, I could modify SignEdit for Bukkit to pretend to break and replace sign blocks, but that behavior is not compliant with the API.

Also…

> Only way I can see this happening is if you place a sign, then someone claims the land while you're typing up the text...?

This edge case is indeed one vanilla + GriefPrevention way to modify a sign in a forbidden claim.  This pull request would fix that case!

**Comment by Deltik** [comment]
> I assume it's for compatibility with a sign editing plugin that doesn't fire any standard building events. Really, the sign editing plugin should fire a BlockPlaceEvent for the sign as a catch-all, but it would be good for GP to also check this.

@Jikoo: I looked into the other events, particularly [`BlockBreakEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockBreakEvent.html) and [`BlockPlaceEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockPlaceEvent.html) as if the sign were broken and replaced, but they do not make sense in the context of the documented behavior in the Bukkit API.  In the API docs, [`SignChangeEvent`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/SignChangeEvent.html) is described as "Called when a sign is changed by a player."  [SignEdit for Bukkit fires this event as documented.](https://github.com/Deltik/SignEdit/blob/fde4032f248145910be266b914978fffe495daf5/src/org/deltik/mc/signedit/SignText.java#L100)

`BlockBreakEvent` could be called, but the sign block never actually breaks during the sign edit operation, and `BlockPlaceEvent` also doesn't make sense because the sign isn't placed again.

Yes, I could modify SignEdit for Bukkit to pretend to break and replace sign blocks, but that behavior is not compliant with the API.

Also…

> Only way I can see this happening is if you place a sign, then someone claims the land while you're typing up the text...?

@RoboMWM: This edge case is indeed one vanilla + GriefPrevention way to modify a sign in a forbidden claim.  This pull request would fix that case!

**Comment by Jikoo** [comment]
> I looked into the other events, particularly `BlockBreakEvent` and `BlockPlaceEvent` as if the sign were broken and replaced, but they do not make sense in the context of the documented behavior in the Bukkit API.

Lecterns call a BlockPlaceEvent with the new state when a book is placed. I think this would be a similarly appropriate behavior that would greatly increase your compatibility across the board.

Again, I think this is a good thing for GP to add, but you can also make a best effort on your end. How many protection plugins do you plan to PR? Old SignEdit (at least, the one I used back in the day, think it was by TimR?) used to call a BlockPlaceEvent to ensure players had permission to modify blocks for maximum compatibility.

**Comment by RoboMWM** [comment]
> This edge case is indeed one vanilla + GriefPrevention way to modify a sign in a forbidden claim.

I wouldn't say so - the player got the sign in before someone "poached" the land so to speak.

**Comment by Deltik** [comment]
@Jikoo: I've done my part and released an [update to SignEdit for Bukkit](https://github.com/Deltik/SignEdit/releases/tag/v1.12.2) that allows the administrator to configure whether to [fire the `BlockBreakEvent` and `BlockPlaceEvent`](https://github.com/Deltik/SignEdit/blob/v1.12.2/src/org/deltik/mc/signedit/integrations/BreakReplaceSignEditValidator.java).

Is this pull request acceptable for validating permissions on sign text changes?

**Comment by Jikoo** [comment]
Looks good on my end. Robo's the one with final say, but I don't see how this could harm anything and it'll futureproof us in case vanilla ever does add it.

**Comment by RoboMWM** [comment]
I guess the only thing I'd like (which I can add later as well when I find time) is a note about how this logic isn't currently necessary/will always be allowed in vanilla Minecraft. (Besides the edge case, which IMO the player has the right to "finish" their action so to speak.)

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
