### PR TITLE
Make DataStore#getGroupBonusBlocks(UUID) public

### PR DESCRIPTION
**Pull request by MineTheCube**
This improve compatibility with external plugins

### CODE REVIEW

**Comment by MineTheCube** [comment]
Could you make a new release with this fix ?

**Comment by RoboMWM** [comment]
You can compile the repository with maven. Otherwise, I'd like to release some other things (there's a couple bug reports, might need to make changes) along with this. Latest I'll push this out is at the end of the week.

**Comment by MineTheCube** [comment]
Ok thanks. And do you have a maven repository ?

**Comment by RoboMWM** [comment]
No, but I plan to get this in the open sonatype w/e repository whenever I have the time to figure out how to set that up (or a PR to do that would also be welcome).

**Comment by MineTheCube** [comment]
I just found this: https://jitpack.io/#TechFortress/GriefPrevention/master-SNAPSHOT
It seems to be like a maven repository that builds directly from Github sources.

**Comment by RoboMWM** [comment]
Oh wow, that looks interesting. I might start using that myself. Let me know if it works, and I'll add it to the readme.

**Comment by MineTheCube** [comment]
It seems to work great :)
See build here: https://travis-ci.org/games647/ScoreboardStats/jobs/161703686

It has compiled successfully, but didn't passed the test though.

**Pull request merged**
