### PR TITLE
Fix for ProtectHorses not including new 1.11 entities (#93)

### PR DESCRIPTION
**Pull request by Rodzynus**
Knowing my lack of experience in programming it's probably horrible way of fixing that, but it seems to work.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Are you able to test this?

**Comment by Rodzynus** [comment]
Yes, I compiled it, replaced original version on my server and players reported that they can ride their donkeys, mules etc., on other peoples' claims as they used to.
Changing ProtectHorses setting to 'true' also works as intended and prevents people from mounting where they don't have permissions.

**Comment by Jikoo** [comment]
Check `entity instanceof AbstractHorse` instead, much cleaner.

**Comment by bigpresh** [comment]
I'd agree - all of them inherit from `AbstractHorse`, so checking that would be sane.  It also means it will likely Just Work for any other future horse-like creatures that may be added to the game :)

**Comment by Rodzynus** [comment]
That's a very good point. I'll edit and test that when I get time later today.

**Review by RoboMWM — APPROVED** [review]

**Review by bigpresh — APPROVED** [review]

**Pull request merged**
