### PR TITLE
Treat glow item frames like item frames

### PR DESCRIPTION
**Pull request by akdukaan**
Fixes an issue where players can remove items from glow item frames in claims

### CODE REVIEW

**Review by RoboMWM — CHANGES_REQUESTED** [review]
I think you will also need to modify `api-version` in plugin.yml?

and as per usual please test, thanks!

**Comment by akdukaan** [comment]
I just tested it on my production server and it works fine. It worked even before I changed the api-version.

**Comment by Jikoo** [comment]
> It worked even before I changed the api-version.

The point of changing api-version isn't that it's required for 1.17, it's that the change will cause a partial breakage on 1.16. Better to clearly fail fast than appear to work and then break later.

**Comment by RoboMWM** [comment]
Although this could be viewed as a bug in the plugin's intended goals, its nature is a new feature (as we're accounting for a new block (new feature) introduced in a new version), so testing and reporting behavior of new feature is more desirable than "it works". But yea, if someone were to update GP while staying on MC 1.16 they'd be complaining about playerinteractevent spam.

**Review by RoboMWM — APPROVED** [review]

**Comment by giantfurkii** [comment]
how to download ?

**Pull request merged**
