### PR TITLE
Fix sync chunk loads in CleanupUnusedClaimTask and DeliverClaimBlocksTask

### PR DESCRIPTION
**Pull request by jok-dev**
Using PaperLib, CleanupUnusedClaimTask will now asyncronously and sequentially (one by one, waiting for the last chunk to load and the required action be completed) cleanup the claim chunks. 

DeliverClaimBlocksTask now checks that the chunk the player is in is loaded before attempting to check if they're in a fluid (this can cause sync loads otherwise). The player is obviously not AFK if they are in an unloaded chunk.

By using PaperLib, it ensures that the plugin will still work on older versions without async chunk api support, but still take advantage of it on newer versions.

Tested and working on 1.15.2 Tuinity (paper fork).

### CODE REVIEW

**Comment by RoboMWM** [comment]
I know about PaperLib and have used it in some of my projects. In other projects, I just flat out use the Paper API with some/no regard for spigot/craftbukkit compatibility. I've been trying to keep this projects remain at its original compatibility (craftbukkit) and introduce no dependencies so that it remains focused on what it delivers. Even the WorldGuard dependency has caused issues.

That being said, I'm 100% for addons that modify/redirect GP to use better implementations, and this is where I'm trying to direct the v20 work - so addons can modify functions of the plugin (e.g. database storage for claims).

**Comment by RoboMWM** [comment]
Also, most servers don't actually use the cleanupunusedclaimtask, only a few servers have this enabled for survival worlds and few have creative worlds - and most of the work is done sync anyways.

> The player is obviously not AFK if they are in an unloaded chunk.

I'm not sure of a case where a player could be in a valid, unloaded chunk in the first place. Even on login the chunk the player is in has to be loaded sync if not already loaded afaik.

**Comment by jok-dev** [comment]
PaperLib is a shaded dependancy, it will not break support with any older versions. The issue with the cleanup task is that it causes sync loads, the actual work that is does is not causing performance issues. We have a server with 150 players concurrent on 1.15, so we need all the performance we can get. 

As for the DeliverClaimBlocksTask, I know that this has caused sync loads in the past, and so surely that is all that matters.

I have provided sparks to show the two issues I have resolved with this PR:

CleanupUnusedClaimTask: https://sparkprofiler.github.io/#dzO7RERhIy
DeliverClaimBlocksTask: https://sparkprofiler.github.io/#WU9SGYfBfp

**Comment by RoboMWM** [comment]
> PaperLib is a shaded dependancy, it will not break support with any older versions. 

Yes, I'm aware of what this is. I'd like to avoid making this plugin fatter than it already is.

> DeliverClaimBlocksTask now checks that the chunk the player is in is loaded 

I'm confused, how is this the case? Yes I see the trace in the sampler there, not sure why it would be causing chunk loads, but the player always has to exist in a loaded chunk, afaik.

**Comment by jok-dev** [comment]
Is 20kb really worth worrying about for improved performance?

I'm not totally sure either, but since the chunks are loading async, it is possible to be in an unloaded chunk. A player move and many other various things could also cause a sync load, but without moving I believe it is possible. Why not do the free check, just incase?

**Review by iLemon — DISMISSED** [review]
Sync loads significantly impact performance on 1.15 at high player counts so this is necessary

**Review by gp-Airee — DISMISSED** [review]
This would make it viable to actually enable this very important option on our server.

**Comment by RoboMWM** [comment]
Hmm, I guess I didn't really emphasize it here, but the cleanup task is going to move away from GP to be the responsibility of an addon (as will the large majority of the features provided by the "creative" claims mode).

And I'm still not sure how or why block delivery is being done async.

**Pull request closed without merging**
