### PR TITLE
Allow adminclaim /trapped

### PR DESCRIPTION
**Pull request by erik1988**
Its now possible to allow players to use /trapped inside adminclaims.
Note that it is off by default.

### CODE REVIEW

**Review by RoboMWM — COMMENTED** [review]
Probably would change the config option wording to AllowTrappedInAdminClaims instead, with default as false (existing behavior). Also would use "unsuitable locations found" if enabled... if that message exists (not sure if it does, right now can't check though).

**Comment by erik1988** [comment]
I reworded it now. not sure If i understand the second part. all i did was to disable the checking of adminclaims if true. The adminclaim message was already there.

**Comment by RoboMWM** [comment]
> not sure If i understand the second part. all i did was to disable the checking of adminclaims if true. The adminclaim message was already there.

~~Yes, because his assumption is that players can get themselves out of administratively-claimed areas. Thus, there's no attempt to find a suitable location. If this option is set to true, then we do attempt to look for a suitable area - and it would be more appropriate to check if such a location exists.~~

Nevermind I just confused myself completely. I was under the assumption that it states "you can build here" when doing /trapped in an admin claim. I guess this changed some time later.

**Comment by erik1988** [comment]
Alright, so we are good to go then?

**Comment by RoboMWM** [comment]
Relevant info as to why this wasn't instated before: https://www.spigotmc.org/threads/griefprevention.35615/page-57#post-1028762

**Comment by erik1988** [comment]
Yeah I know, he answered me. But not every server is the same. For him /trapped inside a admin claim might not be a good thing, but for me it is.  I for instance dont have a special way players must exit. At the same time I have many admin claims around so it happens time after time that players get stuck. If people dont want it, they dont have to turn it on, but me and many others want to allow it.

Agree?

**Comment by RoboMWM** [comment]
Yea I'm aware, just pasting it here because it was related in case I ever need to refer to it (or others).

**Pull request merged**
