### PR TITLE
Fixes Wither Explosions not activating on Hit in Unclaimed Land

### LINKED ISSUE #2037: Withers do not destroy blocks around them when hit.
### Observed Behavior

A wither spawned in an unprotected area, below sea level with not destroy the surrounding blocks around it when attacked.

The wither will however destroy blocks in the same location with its skull throwing.

By testing with events the relevant event being thrown is:

    For wither skulls being shot the event is: 
    
    @EventHandler
    public void on (EntityExplodeEvent event) {
        if (event.getEntity().getType() == EntityType.WITHER_SKULL) {
            System.out.println("I shot a skull");
        }
    }
    
    For the wither breaking surrounding blocks when being attacked the event is:
    
    @EventHandler
    public void on (EntityChangeBlockEvent event){
        if (event.getEntity().getType() == EntityType.WITHER) {
            System.out.println("I destroyed blocks.");
        }
    }

@

### Expected Behavior

That when my players hit the wither while being under sea level and outside of a claim, the wither will then break the blocks around it. 

### Reproduction steps

Download GriefPrevention.
Run the Server.
Go to Y = 0 just to be sure you are under sea level.
Spawn the wither.
Punch the wither.

Then disable GriefPrevention.
Punch the wither.

https://streamable.com/rsoobp

Video was too long to upload normally.

### Stack trace or error log

```shell
There is no error log.
```

### Server version

```shell
[02:55:26 INFO]: Current: git-Purpur-1957 (MC: 1.19.4)*
Previous: git-Purpur-1916 (MC: 1.19.3)
* You are running the latest version
```

### GriefPrevention version

```shell
> version GriefPrevention
[02:57:49 INFO]: GriefPrevention version 16.18
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    buildworld: -1
    cubeworld: -1
    challengeworld: -1
  Claims:
    Mode:
      challengeworld: Disabled
      buildworld: Disabled
      world_nether: Survival
      world_the_end: Survival
      cubeworld: Survival
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 2000
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 10000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 10
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 10
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -100
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 14
      UnusedClaimDays: 21
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      buildworld: true
      cubeworld: true
      challengeworld: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 5
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list

```shell
[03:37:28 INFO]: Bukkit Plugins: (33):
[03:37:28 INFO]:  - BarrelSorting, BeeSafety, BigDoggo, Challengeworld, CoreProtect, CropNoTrample, Cube, DeathPoint, DiscordSRV, ElytraSafety
[03:37:28 INFO]:  floodgate, Geyser-Spigot, GriefPrevention, LuckPerms, MobShop, MoreMobHeads, NBTAPI, NewPlayers, Noaivillager, PerPlayerLoot
[03:37:28 INFO]:  PlugManX, Recipy, SheepNoEat, Silkables, Simpleton, SmoothSleep, spark, ViaBackwards, ViaVersion, WorldEdit
[03:37:28 INFO]:  WorldGuard, WorldUnloader, Zombiechange
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [x] I attempted testing for the issue on a new server.
- [x] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [x] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

### PR DESCRIPTION
**Pull request by TreemanKing**
Closes #2037 

Added a configuration option to preserve previous compatibility.

P.S. Sorry Jikoo for being a clown!

### CODE REVIEW

**Comment by TreemanKing** [comment]
Probably better to reword the Configuration to be WitherOnHitExplosions.

**Comment by Jikoo** [comment]
You're good - I also missed the wiki entry detailing the behavior, and honestly now that it's been pointed out I remember missing it when seeing the first issue I had linked. I spent over an hour scratching my head while creating test plugins and diving into NMS to figure out what the heck was even supposed to be happening. You may have been more vocal about "what do you mean" than I was, but it took you way less time to grasp than it did me. I also apologize about being so abrupt, I definitely could have presented test cases and reproduction in a lot less abrasive manner.

Personally I feel like it doesn't need additional config and should follow the same logic wither skulls use.

**Comment by TreemanKing** [comment]
> You're good - I also missed the wiki entry detailing the behavior, and honestly now that it's been pointed out I remember missing it when seeing the first issue I had linked. I spent over an hour scratching my head while creating test plugins and diving into NMS to figure out what the heck was even supposed to be happening. You may have been more vocal about "what do you mean" than I was, but it took you way less time to grasp than it did me. I also apologize about being so abrupt, I definitely could have presented test cases and reproduction in a lot less abrasive manner.
> 
> Personally I feel like it doesn't need additional config and should follow the same logic wither skulls use.

I've removed the configuration for the time being.

**Comment by ghostlyscythe** [comment]
Ooo a fix? I'm all for it, and willing to test it.

**Comment by TreemanKing** [comment]
> Ooo a fix? I'm all for it, and willing to test it.

Have a go.

https://ci.appveyor.com/api/buildjobs/ideoaqcsbxkkbx12/artifacts/target%2FGriefPrevention.jar

E/ Just try this direct link (@ghostlyscythe)

**Comment by ghostlyscythe** [comment]
Cant seemingly click on anything that comes up? 
https://i.imgur.com/Uao2MOV.png

**Comment by RoboMWM** [comment]
idk if I'm missing it or something but I don't see any config option here

**Comment by ghostlyscythe** [comment]
This does indeed fix the issue, sorry it took so long to get back to you. Had something to do.

**Comment by TreemanKing** [comment]
> idk if I'm missing it or something but I don't see any config option here

I removed it per request and then squashed. Would you like me to add it back?

**Review by RoboMWM — APPROVED** [review]

**Review by RoboMWM — CHANGES_REQUESTED** [review]
> > idk if I'm missing it or something but I don't see any config option here
> 
> I removed it per request and then squashed. Would you like me to add it back?

I was reviewing it quickly and I was going off of the original PR message cuz the discussion got confusing for me to follow lol. Looking at this again now I see what's happening and why and yes this is good to go - the only consideration, which now that I've double checked and am changing my review lol, is that blocking explosions at sea level (or other configured value) doesn't appear to be accounted for

**Comment by TreemanKing** [comment]
> > > idk if I'm missing it or something but I don't see any config option here
> > 
> > 
> > I removed it per request and then squashed. Would you like me to add it back?
> 
> I was reviewing it quickly and I was going off of the original PR message cuz the discussion got confusing for me to follow lol. Looking at this again now I see what's happening and why and yes this is good to go - the only consideration, which now that I've double checked and am changing my review lol, is that blocking explosions at sea level (or other configured value) doesn't appear to be accounted for

I believe it may act above sea level as well, I'll run a test of the build to see if this is the case.

**Comment by RoboMWM** [comment]
Have you been able to test this @TreemanKing ?

To clarify, explosions should be allowed/not canceled if above sea level.

**Comment by TreemanKing** [comment]
> Have you been able to test this @TreemanKing ?
> 
> To clarify, explosions should be allowed/not cancelled if above sea level.

Hey, sorry for the late reply. Explosions are allowed and can work regardless of y-level.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
