### PR TITLE
Change all files ending with CRLF to LF

### LINKED ISSUE #957: Change all files to LF/CRLF file ending
My preference goes to the LF eol.

### PR DESCRIPTION
**Pull request by FrankHeijden**
* Adds a .gitproperties file describing LF as standard
* Changed .editorconfig eol to LF
* Fixes #957

### CODE REVIEW

**Comment by FrankHeijden** [comment]
It's best to review this PR in your IDE as github can't handle the line changes :)

**Comment by RoboMWM** [comment]
It actually can if you have it hide whitespace changes.

**Comment by RoboMWM** [comment]
I do wonder how this will work on Windows though when git is auto-converting line endings to CRLF

**Comment by FrankHeijden** [comment]
> I do wonder how this will work on Windows though when git is auto-converting line endings to CRLF

Why would git autoconvert to CRLF? It's now set to LF

**Comment by RoboMWM** [comment]
https://stackoverflow.com/a/20653073

`core.autocrlf` is set when you install git bash on Windows, and the default is `true.` Therefore, git is responsible for performing the conversion transparently. So, if there's an issue with line endings, then I'd presume there's a command or procedure for git to fix this issue. I haven't had time to look into it yet, as I recall doing it once and I think I had to trudge through different scenarios to fit the issue with whatever environment I saw the issue on (Come to think of it, I think the issue was due to an outdated version of git that didn't perform conversions properly.)

**Comment by RoboMWM** [comment]
https://github.com/TechFortress/GriefPrevention/issues/957#issuecomment-688296063

**Pull request closed without merging**
