### PR TITLE
Hyperconomy hook

### PR DESCRIPTION
**Pull request by mb243**
Add softdepend for HyperConomy for it's internal hook into vault.

### CODE REVIEW

**Comment by Jikoo** [comment]
There are a LOT of economy plugins, adding specific ones to the plugin.yml seems like a bad solution. If there's a problem with GP not using the correct economy it would be better to support all economies by setting up in a task and refreshing whenever a plugin enables or disables.

**Comment by Ceees2** [comment]
I think this should be handled by Vault.

**Review by RoboMWM — APPROVED** [review]
I guess this is okay for the legacy version; anyone's free to PR akin to what Jikoo suggests. Version 20 will "outsource" economy functions to an addon, as it should be (since the few that use it usually want a limit or other customizations).

**Comment by RoboMWM** [comment]
I'll add this in myself I guess, but the right way to do this is as jikoo mentioned, or to check economy status when performing the commands instead.

**Pull request closed without merging**
