### PR TITLE
Addon Plugin API

### PR DESCRIPTION
**Pull request by EtienneDx**
I've added a way for other plugins depending on Grief Prevention to modify it's behaviour directly by registering an Interface instance to act as an hook.

This was based on a modification I made to GP but I'd like it to merge into the main repo since this is where GP get's updated.

Basically, I added an IAddonPlugin interface, an ArrayList of IAddonPlugin in the GriefPrevention class and simply loops over this array in the different methods to check wether the addon plugin blocks the interaction or not.

An example plugin using this modification can be found [here](https://github.com/EtienneDx/RealEstate), with the interesting class [here](https://github.com/EtienneDx/RealEstate/blob/master/src/me/EtienneDx/RealEstate/GP_RealEstateHook.java)

### CODE REVIEW

**Comment by RoboMWM** [comment]
So... Events?

This is already being done in v20

**Comment by EtienneDx** [comment]
Well, it’s not really events, more like blockers for certain actions. I haven’t checked out to what extent you’ve developed the events in the v20, I guess I’ll have a look to see if it’s the same thing or not.

**Comment by Jikoo** [comment]
Personally would prefer to just see GP fire events in those places - Bukkit already has a system in place for this.

Looks clean though 👍

**Comment by EtienneDx** [comment]
hmm, @Jikoo those aren't events tho?
Events are starting an action when something happen, not preventing said action to happen?

**Comment by Jikoo** [comment]
>Events are starting an action when something happen, not preventing said action to happen?

Er, what do you mean events don't allow you to prevent actions? What do you think happens when you cancel a BlockBreakEvent? Events can take whatever form is required for the intended design.
Your IAddonPlugin's methods are essentially the same as listeners registered for events fired when trust is checked. However, in your design GP's default behavior cannot be overridden and the first addon to handle the "event" always has final say.

Basically, I'm good with what you have because it's a minimal change that increases addon capabilities, but it feels like you're trying to reinvent the wheel in a way that doesn't benefit GP nearly as much as it could.

Were I to implement this myself, I would likely include a GPClaimPermissionCheckEvent or something instead (name's a bit verbose for my taste, I'd workshop that down). Would probably contain an OfflinePlayer being checked, ClaimPermission desired, and Claim affected as parameters. I would move the actual GP checks into a helper method that set up the event in its base form (i.e. if permission denied by default, include message and cancel) and then pass it to Bukkit's event system.
I.E.
```Java
    public String allowBuild(Player player, Material material) {
        GPPermCheckEvent event = new GPPermCheckEvent(this, player, ClaimPermission.Build);
        event.setDenialMessage(this.getBuildMessage(player, material));
        Bukkit.whatever(event); // Forgive this, I don't have the API open and it's been a while
        return event.getDenialMessage();
    }
```
Obviously rough, obviously has holes - addon isn't passed material, etc. - but event order is respected and addons can override default behavior.

**Comment by EtienneDx** [comment]
Oooh!
My bad, I'm used to the CSharp "event" keyword which is just a function call, not a cancellable event (if I recall correctly)

Of course, those kind of events would be a perfect match for what I'm trying to achieve. I haven't really had the time to read through all the code yet so I didn't understand ^^'

Therefore I just have a few questions before I close this PR:
- Is the v20 supposed to be released in a matter of days or should I just make a new release with my modified version for my pending changes?
- Is there any work I can help with regarding the v20? (Events are v20 only feature right?)
- I made another "plugin" that helps cleanup heavy config code, it's [AnnotationConfig](https://github.com/EtienneDx/AnnotationConfig), would you merge a PR using this to clarify a little the config code?

**Comment by Jikoo** [comment]
> * Is the v20 supposed to be released in a matter of days or should I just make a new release with my modified version for my pending changes?

v20 is still a ways out, Robo's the only one working on it - I'm mostly just a collaborator for issue assistance and suggestions. I'd definitely like to see this added sooner rather than later, there've been a few dozen issues that could have been resolved by a system like this.

> * Is there any work I can help with regarding the v20? (Events are v20 only feature right?)

I'm sure Robo would welcome help, but you'd want to discuss where your effort would best be spent with him. Events aren't v20-exclusive but v20 will focus much more on providing them, allowing addons to much more readily manipulate GP's behavior.

> * I made another "plugin" that helps cleanup heavy config code, it's AnnotationConfig, would you merge a PR using this to clarify a little the config code?

I'm all on board for anything that improves readability and ease of use, but Robo is in charge. Would probably wait for his OK before investing your time.

I believe Robo hangs out in Spigot's IRC if you do want to have a more interactive conversation about any particulars.

**Comment by TomLewis** [comment]
V20 hasnt had any progress in years, Im waiting on a way to re-make siege from the ground up as its own Add-on, but V20 is nowhere even close.
I'm tempted to even switch to GriefDefender at this rate.

Would this pull request help for us to develop our own version of siege using this branch?

**Comment by EtienneDx** [comment]
It could, it doesn't contain all the hooks you might need but it'sq some groundwork for addons.
The problem is that this codebase still contains all siege code too, so you might have some conflicts of commands or actions, idk..

**Comment by TomLewis** [comment]
That sucks

**Comment by RoboMWM** [comment]
Good idea, but probably better to use events instead of forcing plugins to rely on our interfaces, especially given how we're going to work with the events - Bukkit events will be "funneled" and abstracted to allow for easy handling of different events.

**Pull request closed without merging**
