### PR TITLE
Change material names

### PR DESCRIPTION
**Pull request by 112RG**
I don't know why they changed the material names but eh. This also fixes for all claims that do /ct.

Fixing #392

### CODE REVIEW

**Comment by RoboMWM** [comment]
@mirolm did Worldguard change their API again or something? See the appveyor build log.

**Comment by mirolm** [comment]
Yep they changed/refactored the Vector class. Will create PR later today.

Vector should become BlockVector3 which can be imported from com.sk89q.worldedit.math.BlockVector3

**Comment by 112RG** [comment]
I already have a PR ready just need to test but I can leave it if you want todo it @mirolm

**Comment by mirolm** [comment]
@112madgamer if you have it ready add a PR - i have no way to test it, as i do not use WG/WE on my server.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
