### PR TITLE
Fix #72

### LINKED ISSUE #72: [Request] Toggle Mobgriefing in Claims
Hello Github people,

Recently on a server (named Dawnhaven) I've discovered the need for mobgriefing to be on.
Why? Because a recent machine I've been creating in my SP test worlds used Wither mobgriefing in order to break cobblestone, fed into a Wither cage by pistons.
While I (and friends) are trying to convince the server owner to turn mobgriefing off (because the spawn rate of hostile mobs on the server is really low), I was wondering if you all could code it so there could be a /claimmobgrief command that turns mobgriefing on and off in that claim.

Thanks, 
Meta

### PR DESCRIPTION
**Pull request by ghost**
Allow withers to respect the claim explosions flag so they can break blocks if allowed :3

### CODE REVIEW

**Comment by RoboMWM** [comment]
So idk what metrics Big_Scary used to determine it's too expensive to check. Obviously on low population servers this is no issue, and that comment implies he did something like this before.

**Comment by ghost** [comment]
This method was optimised by the Spigot team in 1.9, so its performance usage should be a major difference compared to what it used to be.

**Comment by RoboMWM** [comment]
Mind linking the commit(s) in interest? The only explosion optimizations I'm aware of is the removal of calculating explosions on dead entities in Paper.

**Review by RoboMWM — DISMISSED** [review]
Hmm, I guess this is okay. Still curious though about the supposed performance cost to doing this before.

Just fix the conflict via making the change in the refactored path and it'll be good to go.

**Comment by ghost** [comment]
@RoboMWM Resolved :)

**Comment by RoboMWM** [comment]
Hmm you did merge but uhm... idk why the PR is still saying there's a diff with 69 changed files...

**Comment by RoboMWM** [comment]
Merged in https://github.com/TechFortress/GriefPrevention/commit/2f5a2eea9c1d16a07d96c74889f9bcdd13a65cc4

**Pull request closed without merging**
