### PR TITLE
Add config option for mob projectiles changing blocks in claims

### PR DESCRIPTION
**Pull request by Swordstone86**
Some builds that rely on mob projectiles changing blocks, like TNT-powered music disc farms where skeleton arrows must ignite TNT, are completely broken in claims. `EntityEventHandler.handleProjectileChangeBlock` handles these interactions but only allows projectiles to change blocks if:

1. The area is unclaimed, or
2. The projectile was shot by a player who is trusted in the claim, or
3. The projectile was shot by a dispenser in the same claim.

There's no exception for mob projectiles and no way to allow mob projectiles to change blocks, so I went ahead and added a config option to do just that. This allows TNT music disc farms and other builds relying on the mechanic to work again, as tested on a Paper 1.20 server.

The default for this config value is false, which means default behavior is unchanged unless a server owner specifically toggles `MobProjectilesChangeBlocks` to `true`.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Given that other mob grief is allowed, I'm thinking this should be allowed by default too, thoughts?

**Comment by Jikoo** [comment]
Makes sense to me, it's such a niche thing. I guess we could run a target check to make sure the target is either a non-player or trusted if we want to be super safe. Honestly if we do that we probably shouldn't even include a config option.

**Comment by RoboMWM** [comment]
> I guess we could run a target check to make sure the target is either a non-player or trusted if we want to be super safe.

To prevent elaborate player traps? Or am I understanding this wrong?

**Comment by Jikoo** [comment]
> > I guess we could run a target check to make sure the target is either a non-player or trusted if we want to be super safe.
> 
> To prevent elaborate player traps? Or am I understanding this wrong?

To prevent luring skeletons into farms and breaking things with their arrows, for example. If we're guarding against the potential malicious usage I don't see why it needs a config option given how opinionated GP is in general.

**Comment by RoboMWM** [comment]
Ah. Do we do checks like that for e.g. creepers being lured in now too?

My current understanding is that mob-performed stuff, even with hostile mobs, are currently permissible since that's seen to be an issue with how the player has built their structures. E.g., mobs can trample crops.

**Comment by Jikoo** [comment]
That's true, I guess this does fall under general mob grief, which GP does have config settings for.

**Comment by RoboMWM** [comment]
I'll want to revisit this sort of stuff with v17 - my thinking is to simplify config to either deny all or allow all, and have addons provide more granular controls later on.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
