### PR TITLE
Option to ban for profanity rather than mute

### PR DESCRIPTION
**Pull request by akdukaan**
On my server, I have my bannedwords set to just the N word. From what I've noticed, the players who get softmuted would always cause trouble later by using hacked clients, griefing, or some other way. The option to ban for profanity rather than mute would help me and other server owners handle them better.

### CODE REVIEW

**Comment by RoboMWM** [comment]
You must have quite the dedicated players then or are engaging with said players somehow, as a softmute usually is sufficient for starving attention away from those in chat. And usually the ban on spam should catch those players too. This seems a bit overkill and would probably just lead to alt accounts IMO...

**Comment by akdukaan** [comment]
Logically, what you described is what I would expect too. But in my experience, that hasn't been the way things have gone. This option will also give server owners the ability to avoid the problem where softmuted players' messages still show up on Discord because of the DiscordSRV plugin.

Also, I meant to remove that sentence about this PR being unfinished after I made the most recent commit, so I'm going to mark it as 'ready for review' now.

**Comment by Jikoo** [comment]
Re: softmuted messages in Discord - should probably contact DiscordSRV and ask them to add a feature that doesn't post messages that aren't sent to all online users. That's a basic thing they should be doing anyways to support things like non-global channels in chat plugins.

**Comment by akdukaan** [comment]
Re: softmuted messages in Discord - If they did that, wouldn't that mean that if any online player has another player ignored with the essentials /ignore command, then that message wouldn't be posted to Discord? I'm not sure if that's the best solution.

**Comment by Jikoo** [comment]
Re: softmuted messages in Discord - Valid point, but unfortunately, softmute is basically forced multi-ignore. You could also think of it like a chat channel - users can see and post to it, but users who aren't in it can't see it.

/e: I will admit though, this was a frustration for me with Dynmap, and what I ended up doing there was cancelling all chat, manually sending it myself so I could use JSON components, and manually re-sending Dynmap the eligible stuff.
I also actually fully disabled and partially re-implemented GP's entire player chat listener to remove the features I disliked and rework the spam system to be more forgiving, but it was a hack.

/e2: I guess the point I'm trying to make here is that chat is a really fiddly thing and there's almost no way to make all possible options work properly, especially in a case like an IRC relay or Discord bridge. While I'm sure DiscordSRV could add support (or an addon? Do they fire an event for posting chat? I dunnno) it's unfortunately something that will not play well out of the box due to the limited nature of information passed between events.

**Comment by JustDoom** [comment]
This would be really useful, Please add this

**Comment by saboooor** [comment]
This would be really useful, Please add this

**Comment by amnoah** [comment]
Edited

After a talk with DrBot, here is my suggestion on this

I could see how this could be useful for things like slurs. Just ban racist or homophobic players. Similar to the mute word Bank, add a bank for ban words and a separate toggle. This way its fully configurable

**Comment by RoboMWM** [comment]
Thinking about this, I think it'd be better to expose API for this instead so addons can choose how to deal with such people accordingly.

**Pull request closed without merging**
