### PR TITLE
Remove economy, vault dependency

### LINKED ISSUE #1151: Remove vault dependency
Superfluous feature that has lent to other economy-related feature requests such as buying/selling claims and such.

Bonus and accrual blocks distinction will remain though since GP's primary/built-in way to deal with a "claimblock economy" is via playtime, and bonus blocks provides a way to easily override or augment that.

### PR DESCRIPTION
**Pull request by RoboMWM**
vault and economy go bye bye

will close #1151

### CODE REVIEW

**Comment by RoboMWM** [comment]
@qartho

Just requesting reviewers just to see if my changes are sane before I click the red button to put 'em in.

**Comment by QarthO** [comment]
I think you'll also want to remove the messages from the Messages enum

**Comment by QarthO** [comment]
Looks good to me

**Comment by RoboMWM** [comment]
Coolio, thanks.

**Pull request merged**
