### PR TITLE
Change repository of VaultAPI

### PR DESCRIPTION
**Pull request by jyhsu2000**
Because the repository of VaultAPI has been offline for days.
And still no response from the author.
I suggest we can use the repository provided by EssentialsX Team instead.

Reference to  https://github.com/MilkBowl/VaultAPI/issues/69#issuecomment-464878181

### CODE REVIEW

**Review by RoboMWM — DISMISSED** [review]
Yes I've been doing that too with other projects.

I'd suggest renaming the maven id but w/e not big deal.

**Comment by RoboMWM** [comment]
Seems he's going the jitpack route, but hasn't updated any readme's yet.

**Comment by jyhsu2000** [comment]
> Yes I've been doing that too with other projects.
> 
> I'd suggest renaming the maven id but w/e not big deal.

Sure. I just renamed it to `essx-repo`

> Seems he's going the jitpack route, but hasn't updated any readme's yet.

Who is `he` here? The author of Vault?
Jitpack is also a solution and I just simply chose one of feasible solutions.

**Comment by RoboMWM** [comment]
Maintainer of vault, yea.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
