### PR TITLE
Support 1.20.4 changes - SHORT_GRASS and  EntityDamageByEntityEvent changes

### PR DESCRIPTION
**Pull request by QarthO**
Temporary fix for https://github.com/GriefPrevention/GriefPrevention/issues/2214

The fix was to add a DamageSource in the event constructor.
This required to update the minimum required version to 1.20.4

~~This build will error since it doesn't include the GRASS to SHORT_GRASS change, which has been fixed in this PR: https://github.com/GriefPrevention/GriefPrevention/pull/2217~~

Update: GRASS to SHORT_GRASS changes have been added

This change in my opinion is a temporary change to get a working version out. But this will need to be looked at in the future. We shouldn't be constructing new Events to rerun code. All of our event listeners are due for a rewrite in future versions.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Go ahead and put the PRs together, since this really is a "1.20.4 update" and make change to plugin.yml.

Makes me a bit hesitant to release this (well, if you push this to legacy as well which I assume you will) since you're gonna get ppl who complain who are on older patch versions, but it be whatever.

**Comment by QarthO** [comment]
want me to push these on the legacy branch?

**Comment by RoboMWM** [comment]
Up to you, a quick and dirty fix. If we gonna add short_grass which you've done already, we might as well just do it anyway then.

**Comment by QarthO** [comment]
yeah dirty changes, just got to get a working build out. Looking forward to wrapping this up and beginning the process of rewriting alot. Seems like gp is full of these quick and dirty changes

**Review by RoboMWM — APPROVED** [review]

**Comment by RoboMWM** [comment]
Since spigot isn't updated yet, and this requires a newer build of the same patch version for paper and other forks, I'm more hesitant on having this for legacy now. Probably better to do whatever quick fix that doesn't involve constructing event for legacy, no matter how ugly.

**Pull request merged**
