### PR TITLE
Make migration process async

### PR DESCRIPTION
**Pull request by bilektugrul**
I've made FlatFile to SQL data conversion async with 2 seperate tasks for claims and player datas. It also has a tracker task that informs about progress and when conversion is done, it backups old folders and closes everything.

### CODE REVIEW

**Comment by bilektugrul** [comment]
This was necessary for our server with a lot of claim and player data. It speeds up the process quite a bit, but it could be so much faster. Since it is a one time process for us, I did not bother to change it that much. Maybe in the future.

**Comment by Jikoo** [comment]
Personally, I don't like this.
Players should not be able to access area in unmigrated claims they don't have trust in. The fact that the server is playable in this version is a major detriment in my mind. The status reports are nice, but could be handled by a time check inside a blocking loop. Adding a config node for something that should be a one-time process feels a little silly, people can deal with a couple extra messages in their console for the few minutes that it takes.

I don't like the inclusion of removing logging errors with loading a claim. Per the discussion in #1068, clobbering the error and ignoring the file is just sweeping the problem under the rug. I wouldn't object to the file being moved after logging it once, then a smaller warning each startup if corrupted files are stored, but that is probably something better handled by a separate PR.

I think the "correct" solution for making the server playable during migration is to create an intermediary datastore that takes 2 backing datastores - the one migrated from and the one migrated to. The intermediary should load the `from` database and use it for all queries while the `to` datastore is being populated and saved, then switch control when the process is completed.

It's also worth mentioning that GP's database datastore implementation is really awful, and until it gets overhauled, flatfile is actually superior. Since the datastores are slated for v18, that hopefully isn't too far off, but I would recommend waiting on rewriting migration (and migration in general) until then.

**Comment by bilektugrul** [comment]
> Personally, I don't like this. Players should not be able to access area in unmigrated claims they don't have trust in. The fact that the server is playable in this version is a major detriment in my mind. The status reports are nice, but could be handled by a time check inside a blocking loop. Adding a config node for something that should be a one-time process feels a little silly, people can deal with a couple extra messages in their console for the few minutes that it takes.
> 
> I don't like the inclusion of removing logging errors with loading a claim. Per the discussion in #1068, clobbering the error and ignoring the file is just sweeping the problem under the rug. I wouldn't object to the file being moved after logging it once, then a smaller warning each startup if corrupted files are stored, but that is probably something better handled by a separate PR.
> 
> I think the "correct" solution for making the server playable during migration is to create an intermediary datastore that takes 2 backing datastores - the one migrated from and the one migrated to. The intermediary should load the `from` database and use it for all queries while the `to` datastore is being populated and saved, then switch control when the process is completed.
> 
> It's also worth mentioning that GP's database datastore implementation is really awful, and until it gets overhauled, flatfile is actually superior. Since the datastores are slated for v18, that hopefully isn't too far off, but I would recommend waiting on rewriting migration (and migration in general) until then.

Thanks for taking it serious and writing this. I did not put a lot of thought into this, like I said it'll be a one time process for us and we'll be making it in test environment, so I didn't think about the server being playable. I should've considered that GP is a big plugin.  

I can make some adjustments for error handling and it seems really necessary, i just added an int and null check, thats a bit silly knowing that clueless server owners will use it. And I could block player joins while conversion is active.

**Comment by RoboMWM** [comment]
flatfile to sql conversion is deprecated (as well as sql in GP in general). See the roadmap for more info (i.e. current plan is for addons to provide their own storage systems for claims).

**Pull request closed without merging**
