### PR TITLE
Update WE api to support there latest refactor

### PR DESCRIPTION
**Pull request by 112RG**
Still needs to pass in-game testing

### CODE REVIEW

**Comment by 112RG** [comment]
Can't even test as the build with this commit doesn't work. This should at least allow the project to build

**Comment by RoboMWM** [comment]
What commit? You mean worldguard's version 7 is currently broken?

**Comment by 112RG** [comment]
Yeah the build with the latest refactor is broken

**Comment by RoboMWM** [comment]
Hmm in that case, if you can find the last working snapshot build (a la before the refactor) and manually stick that in (instead of SNAPSHOT) that'll be good enough for now so we can at least build GP.

**Comment by RoboMWM** [comment]
In another PR that is

**Comment by 112RG** [comment]
Closing as not supporting this ATM

**Pull request closed without merging**
