### PR TITLE
Fix inconsistencies with damage handling

### PR DESCRIPTION
**Pull request by Jikoo**
De-duplicates code by using a wrapper for the bits of damage events we care about.

Noticed that the environmental check (which probably should be ignored there anyway as we're only listening to the EntityCombustByEntityEvent aka not environment) wasn't actually preventing the environmental damage, just saying it was handled. https://github.com/GriefPrevention/GriefPrevention/blob/b384806e18bbd870e53323c1e8ac719d32bb33d2/src/main/java/me/ryanhamshire/GriefPrevention/EntityDamageHandler.java#L364-L374 Didn't really feel like rereading all the bajillion duplicate lines to see if there were other potential bugs, just re-unified the code.

### CODE REVIEW

**Comment by Jikoo** [comment]
Another potential bug, either with my code or the original and not the API change bandaid: the way we handle combustion events basically just prevents pets from taking fire damage even if it was caused by a fire sword/bow with an allowed attack. We should consider moving from FIRE_TICK to FIRE, listening to the EntityCombustEvent for pets, and no longer treat FIRE_TICK as environmental.

**Comment by RoboMWM** [comment]
entity damage code is probably one of my least favorite parts to look at in this codebase lol. Something that would really benefit from the event funnel system or however we're implementing it.

**Review by RoboMWM — APPROVED** [review]

**Comment by QarthO** [comment]
Makes me wonder if its worth to spend effort slowly applying bandaids overtime, or just completely rewriting/refactoring it and moving it to the com.griefprevention package would be better

**Comment by RoboMWM** [comment]
Legacy branch exists if we ever want to reference the original Big_Scary logic for a rewrite. Otherwise, if others want to PR bandaids that cleanup code, I'm ok with it in master. Ideally I'd just like to delete stuff altogether tbh and reimplement later in v18, but if people PRing want to have their own take on cleaning up code, that's ok.

Major refactors or straight up feature additions to master are the things that I'm currently putting on the backburner for master.

Major refactors to legacy branch will be rejected. New features are 'ok,' provided they are small and deemed 'easily maintainable.'

I'm copying this comment to the roadmap discussion for future discussion if desired.

**Comment by Jikoo** [comment]
Damage handling is a horribly complex beast. Imo ideally eventually we pass it off to users via interpreting rule sets, but I don't see us getting there for a while. I do have loose plans to merge potion/vehicle handling if possible, which should ideally be made a little easier by using a wrapper in place of an actual event.

**Pull request merged**
