### PR TITLE
[Feature] Anti Claim Zone

### PR DESCRIPTION
**Pull request by FrankHeijden**
This feature allows you as a server administrator to disable claiming in a radius around existing claims, to prevent so called "bully"-claims. Players will still be able to build around their claims, but they wont be able to claim it.

Some players might still want to claim next to each other, because they like to play together and/or extend their claims using a multi-person team. Therefore we have the following commands to allow players to "neighbour" with others:

- **/AddNeighbour <Player>** - request a player to be your neighbour, allowing you and that player to claim in each others “no claim zones”
- **/AcceptNeighbour <Player>** - accepts the request
- **/RemoveNeighbour <Player>** - removes a neighbour, notifying both players
- **/RemoveAllNeighbours <Player>** - removes all neighbours, notifying all involved players

The neighbour status is not persistent, and thus will be dropped after a restart. When two players are neighbours, they can claim in each others "AntiClaimZone". When they claimed next to each other and they remove their neighbouring status, they are only allowed to shrink their claim, but not extent anymore because they are in someone else's AntiClaimZone.

To allow moderators/admins modifying existing claims, IgnoreClaims will bypass this restriction.

Claim inspection tool also has been updated to visualise the AntiClaimZone accordingly when clicking in the "AntiClaimZone" of the claim, the blocks for this can be changed in config.yml.

The update is backwards compatible, and will change nothing if the user doesn't enable the option in the config.yml:
```yaml
GriefPrevention:
  Claims:
    AntiClaimZone:
      Enabled: false
      Radius: 10
      DisplayWhenInspecting: true
      DisplayWhenShiftInspecting: false
      CornerBlock: SEA_LANTERN
      AccentBlock: PRISMARINE
```

### CODE REVIEW

**Comment by bigpreshkt** [comment]
I respect the effort you've put in to this, but as I said in #505 I see this as unnecessary complexity; if you want a larger area protected, you just claim further out.

It isn't my call though, but I personally would vote against this being incorporated into GP core.  Sorry!

**Comment by bigpresh** [comment]
I respect the effort you've put in to this, but as I said in #505 I see this as unnecessary complexity; if you want a larger area protected, you just claim further out. (This feature was also discussed way earlier in #124 where a similar discussion was had.)

It isn't my call though, but I personally would vote against this being incorporated into GP core. Sorry!

(Reposting same comment from correct GH account this time - d'oh!)

**Comment by FrankHeijden** [comment]
> I respect the effort you've put in to this, but as I said in #505 I see this as unnecessary complexity; if you want a larger area protected, you just claim further out. (This feature was also discussed way earlier in #124 where a similar discussion was had.)
> 
> It isn't my call though, but I personally would vote against this being incorporated into GP core. Sorry!
> 
> (Reposting same comment from correct GH account this time - d'oh!)

Sure this works, but this won't work when you fix a maximum amount of claimblocks players can have and/or when claimblocks are difficult to earn.

I know this adds an additional complexity layer, but I don't know if that's a valid reason to restrain ourselves from adding in new features. In a few of the commits I have tried to reduce the amount of complexity in GP's code itself, a good example of which is the technique used for overlapping claims, which was unnecessarily complex.

In my opinion, we should add in features, but with care and allowing space to refactor a good chunk of the code, which we cannot just do in one commit.

**Comment by FrankHeijden** [comment]
@RoboMWM I really wanted to include this as an addon, but as of right now, it is impossible to implement within an addon. The feature has been a long-requested feature, which I find a valuable reason to implement in GP-core 😄

**Comment by RoboMWM** [comment]
Hi, thanks for the PR!

bigpresh already mentioned how this does not fit in the scope of this plugin.

And since you got your reply in before I started talking about this being suitable as an addon - can you please explain how this isn't possible in an addon?

**Comment by FrankHeijden** [comment]
I'd need the changes from PR #937.

**Pull request closed without merging**
