### PR TITLE
Minor Maven Project Housekeeping

### PR DESCRIPTION
**Pull request by javacraft**
Since project was update to follow Maven convention in June, this PR fixes a few minor Maven convention-related items: 1) test resource directory; and, 2) redundant directory specifications.

Thank you for making GriefPrevention follow Maven conventions. It was something that always nagged me, but did not want to address just in case there were developer sensitivities to other preferences. Thanks for all the hard work.

Best regards,
Frelling

### CODE REVIEW

**Review by RoboMWM — APPROVED** [review]
Weird, I have no idea what you did to Tests.java. It got moved but never changed directory...?

Otherwise looks fine, will pull after other 1.13-related PRs are pulled to avoid potential conflicts.

**Comment by Jikoo** [comment]
>Weird, I have no idea what you did to Tests.java. It got moved but never changed directory...?

src/tests -> src/test, GH's view system isn't very friendly for long paths

**Comment by RoboMWM** [comment]
Figured it was some tiny change, thanks

**Comment by RoboMWM** [comment]
Huh, yea the singular form of `test` is the default. Not sure why the other guy decided to do that plus all the verbosity.

**Pull request merged**
