### PR TITLE
Allow Datastore.getClaim(long id) to return subclaims

### LINKED ISSUE #814: DataStore.getClaim(long id) doesn't return subclaims
### What happened:
I can't get a subclaim by it's id.

### What was expected:
Get the subclaim with it's id

### Steps to reproduce:
Another plugin using getClaim with a subdivision claim id

### Server and GriefPrevention version:
Spigot 1.15.2, latest master (093cbb0)

### Suggestion of fix
Iterating over each subclaim while iterating over the claims to find the corresponding one.

Current code:

https://github.com/TechFortress/GriefPrevention/blob/093cbb0e93b3ce33c2071efcc0e2bc438a0c7d46/src/main/java/me/ryanhamshire/GriefPrevention/DataStore.java#L747-L755

I'll fix it into my fork, it's gonna get added into #811 (I can make it another PR too, I just had the bad idea of staying on my master branch over there so yeah...)

### PR DESCRIPTION
**Pull request by akdukaan**
Code copied from https://github.com/TechFortress/GriefPrevention/pull/811 which I think was closed because it tried to take on way more than just this fix

Closes https://github.com/TechFortress/GriefPrevention/issues/814

### CODE REVIEW

**Comment by RoboMWM** [comment]
Looks ok, I'll see if @Jikoo has anything to add, but otherwise will pull

**Review by RoboMWM — DISMISSED** [review]

**Review by Jikoo — DISMISSED** [review]
Beyond mixed whitespace, looks good 👍

**Comment by RoboMWM** [comment]
> Beyond mixed whitespace, looks good 👍

Space between the `if`s and `for`s, right? Not sure if you see elsewhere too.

**Comment by Jikoo** [comment]
> Space between the `if`s and `for`s, right? Not sure if you see elsewhere too.

I meant the mix of spaces and tabs, but you're correct, yeah.
image

**Comment by RoboMWM** [comment]
> > Space between the `if`s and `for`s, right? Not sure if you see elsewhere too.
> 
> I meant the mix of spaces and tabs, but you're correct, yeah. image

Interesting are you viewing that in Github?

**Comment by Jikoo** [comment]
> Interesting are you viewing that in Github?

Browser extension, https://github.com/refined-github/refined-github
I don't like a lot of the options (and there are an unfortunate number of them for that), but showing whitespace is lovely. It's the only extension for whitespace I've found that has continued to update as GitHub breaks it over the years.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
