### PR TITLE
remove siege

### LINKED ISSUE #1143: Remove Siege
Siege is mostly unused ([currently at 0.6% of users](https://bstats.org/plugin/bukkit/GriefPrevention-legacy/3295#uses_siege)) and is embedded into a lot of the very messy pvp codebase. Removing siege would help make the process of refactoring the pvp code to a distinct "module" a lot less costly.

### PR DESCRIPTION
**Pull request by RoboMWM**
Closes #1143

### CODE REVIEW

**Comment by Nanpure** [comment]
Hello. We just updated our grief prevention and found that this feature has been removed or disabled. My players were excited to use this feature and we were planning to integrate it into our server's PVP-oriented gameplay extensively. We are very disappointed to see that it has been removed.

Are there any plans to bring it back in some kind of extension module? We were really excited about this feature.

**Comment by QarthO** [comment]
There is no plan to keep siege apart of core griefprevention. It will be something that will need to be maintained by an addon.

However @Jikoo has started the process in making an addon. Not sure how far along in the process he is with it, or if its functional. But feel free to check it out:
https://github.com/GPAddons/GPSiege

**Comment by Jikoo** [comment]
I burned out on making the addon and pushed what I had - the GP implementation was full of holes, and I tried too hard to fix those rather than just slap together something that worked just as well as GP's siege didn't. A real siege addon is a full-scale plugin concept including the support burden, and I don't have any real drive to work on it because siege isn't a feature that interests me. Happy to let anyone take it over if they're interested.

**Comment by QarthO** [comment]
@Nanpure I'm assuming you only updated to the master branch (where siege is removed) because of the chorus fruit change I had made. If you'd like I can get a build together from the legacy branch that way you can have siege and the chorus fruit fix. 
Let me know

**Comment by Nanpure** [comment]
@QarthO Yes, I would love to try that. Thank you.

We have several plugins that depend on GriefPrevention, and we are very happy with the experience. We have looked at alternative land plugins, but none of them have the simplicity and charm of GP.

**Comment by QarthO** [comment]
@Nanpure https://github.com/GriefPrevention/GriefPrevention/pull/2267
Might need to wait a couple of minutes for the build server to make the artifact, but there it is

**Comment by Nanpure** [comment]
@QarthO 
I didn't understand what you meant by artifact in the other thread or where to find it. I ended up cloning the master branch and merging your changes in myself, them building with maven.

Where do I go to download these artifact builds?

**Comment by QarthO** [comment]
Head to the PR, scroll down to the bottom and click on the following
> Show all checks
> Details
> Artifacts
> Then click on target/GriefPrevention.jar

**Comment by Nanpure** [comment]
Fantastic. Thank you. We are very excited to try this out.

**Comment by Nanpure** [comment]
I can see why it was removed. It was completely broken when we tested it. It was enabled for the correct world but blocks could not be broken. There was also no feedback on the status of the siege, which stressed the target, since he didn't know when it was safe to logout. We had him sitting outside of his claim for a while, but it never ended the siege. Finally we had him log off, which killed him.

I love the idea, but it's not working anymore and does not have enough live feedback to make it an enjoyable experience. I see now why it was removed.

As far as not being able to break blocks, I added the world to the config file live and did a /gpreload, which might not have registered it properly. But even if we could break blocks, the players agreed that it was too difficult to tell whether there was an active siege, how long it was supposed to last, and when they were safe to logout.

**Pull request merged**
