### PR TITLE
Using PreparedStatements instead of normal Statements

### PR DESCRIPTION
**Pull request by Ceees2**

### CODE REVIEW

**Comment by RoboMWM** [comment]
Did you test this?

**Comment by Ceees2** [comment]
Yes all of them except the schemaversion update, but I don't expect that would not work.

**Comment by RoboMWM** [comment]
~~I guess I'll go ahead and accept this, but I'm gonna be blaming u if dis breaks ppls serburz :P~~

**Comment by RoboMWM** [comment]
I'll accept this as soon as I get feedback on it, since I do not use the database storage function of this plugin.

**Comment by Jikoo** [comment]
Assuming all of the statements are called on the main thread, the PR looks good, otherwise a new PreparedStatement should probably be created each time. If you ever intend to allow user input (such as #126) this is pretty much required for sanity.

Nitpick: The PR contains a mix of spaces and tabs. This is how things get ugly and messy.

**Review by Gaurav99 — CHANGES_REQUESTED** [review]
Improves overall efficiency substantially, but has the potential for memory leaks.  PreparedStatements are much more efficient than normal statements, BUT they still need to be closed after execution or they can accrue quite the memory leak.  

Also, be sure that the ResultSets are properly closed (before their respective PreparedStatements are closed).

**Comment by RoboMWM** [comment]
@Ceees2 any response to Jikoo's or Gaurav99's comments?

**Comment by Ceees2** [comment]
Hope I did this right, still learning how to use pull requests.

To get back on topic, the PreparedStatements and ResultSets should now be properly closed. I've also changed the space indentations back to tabs.

**Comment by Jikoo** [comment]
GP currently compiles for 1.6 so try-with-resources isn't allowed, but I don't think it's unreasonable to bump that up to 1.8, especially with MC 1.12 requiring it.

**Comment by Ceees2** [comment]
I noticed indeed, Java 6 and 7 support has been dropped by Mojang for a while. I'm wondering why GP is still on Java 6.
https://help.mojang.com/customer/en/portal/articles/2636196-minecraft---java-6-and-7-support

**Comment by RoboMWM** [comment]
> I'm wondering why GP is still on Java 6.

Big_Scary had GP compile on Java 6. I don't mind bumping to Java 8, considering that I already have a warning for those on Java 7 or earlier using the non-java-7 version (since concurrenthashmap isn't "cross-compiler-version compatible")

**Comment by RoboMWM** [comment]
If you guys wish to leave (a new) review go right ahead, otherwise I think it looks okay to me, albeit I have limited SQL knowledge at this time.

**Comment by Jikoo** [comment]
I'll admit I only skimmed it this time, but it looks solid to me.

**Comment by RoboMWM** [comment]
Yea, I had a feeling this would conflict with the other PR. Can you try to fix and update accordingly @Ceees2 or @jacob1?

**Comment by RoboMWM** [comment]
@Ceees2 @jacob1

Some of the conflicts (expectedly) involve the area where the prepared statements were made. Can either of you resolve this conflict? (It appears you can use the web editor to resolve this conflict).

**Comment by jacob1** [comment]
Using a web editor to resolve a conflict seems like a bad idea. It still needs testing. This isn't my PR anyway, but it probably needs to be updated to use prepared statements for the changes I made or something.

I have been very busy recently, hopefully Ceees2 can come fix it (and this still isn't my pull request, lol. To fix it I'd have to make a separate pull request)

Btw here is a link to view the diff without all the whitespace changes: https://github.com/TechFortress/GriefPrevention/pull/99/files?w=1

**Comment by RoboMWM** [comment]
Maybe I should've merged this first :P but he could give you access to his branch if he desires. I've hardly dealt with SQL, much less prepared statements so I don't want to make guesses myself.

Also, how'd you find that ?w=1 trick?

**Comment by Ceees2** [comment]
I hope this did the trick.

**Review by RoboMWM — APPROVED** [review]
Hopefully SQL users don't complain lol

**Comment by Ceees2** [comment]
It should atleast improve performance.

**Pull request merged**
