### PR TITLE
Change claimexplosions permission

### PR DESCRIPTION
**Pull request by 112RG**
Change the permssion of claimexplosions to needing manager trust level addressing issue #742

### CODE REVIEW

**Review by RoboMWM — DISMISSED** [review]
Wow, didn't know that's how he checked for permission.

**Comment by ArtNRG** [comment]
It's better to allow to toggle explosions to the claim owner only instead of permission trust. Claim owners often give somebody permissiontrust to their sub-claims to make a city. Trusted players build their homes there and are able to trust somebody. That players still be able to toggle explosions on and explode everything around that sub-claim.

https://github.com/TechFortress/GriefPrevention/blob/c2aebf07769cb15a39339b1e8af0419b277080dd/src/main/java/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L2035
`
if(claim.allowEdit(player) != null)
{
  GriefPrevention.sendMessage(player, TextMode.Err, Messages.NotYourClaim);
  return true;
}
`

**Comment by 112RG** [comment]
I am not sure that is how it works. When the owner gives permission trust to a subclaim, explosions can only be toggled for that subclaim. Explosions will only damage the subclaim even if the TNT is pushed out by water from my testing. If the main claim has explosions enabled then damage will occur, but I think that is fine since they are opting into explosion damage

**Comment by ArtNRG** [comment]
As I saw on the server, explosions are toggled to the whole parent claim instead of sub-claim even if the command was typed in the sub-claim.

**Comment by 112RG** [comment]
Hmm from my testing when it was enabled in a subclaim explosions didn't damage the main claim. Are you using the build from this appveyor branch?

**Comment by RoboMWM** [comment]
For reference, the current latest build for this PR is https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/31846008/artifacts

**Comment by Jikoo** [comment]
Imo this is not a good change - build trust is permission to break blocks, which is what explosions do. Permissiontrust/management is the ability to trust others up to your trust level, which may be as low as accesstrust depending on use case. I often used to use it at containertrust level in shopping district subclaims so users could let their friends restock their shops but not mess around with the shops' structure. This change would enable those users to toggle claim explosions and then use a TNT cannon to bust down shops.

I wouldn't object to it being an owner-only command, but the original issue cannot be reproduced so I think that may just be unnecessary extra inconvenience to well-behaved players trying to work together.

Edit: actually, knew I'd commented on this sort of change before - here's my hot take: https://github.com/TechFortress/GriefPrevention/discussions/618#discussioncomment-194004

**Comment by RoboMWM** [comment]
Yea, I know I had similar thoughts but I guess since I've considered this low priority I haven't yet commented.

One idea I have is to make /permissiontrust part of the hierarchy above build trust. Not sure if I can properly allow for resizing since it's using the owner's claim blocks, but would effectively allow for other players to "share" ownership of a claim to the highest extent possible (and simplify its handling in the code as well as explaining to users).

**Comment by Jikoo** [comment]
👍 Sounds like a v19 discussion then since we'd need to migrate data to prevent issues with existing managers in claims.

**Pull request closed without merging**
