### PR TITLE
dumbed down header img

### PR DESCRIPTION
**Pull request by QarthO**

### CODE REVIEW

**Comment by Jikoo** [comment]
You guys know if you preview the rich diff you can see the resulting size, right? Also the preview button in general prior to committing when you're editing on GitHub.

**Comment by QarthO** [comment]
the issue here is with jekyll. not the preview on github. its worked perfect on github. no issue on the readme for github. that's not what we're trying to fix

**Comment by QarthO** [comment]
image
^ currently looks great on the readme
but you go to the jekyll site...
image

**Comment by Jikoo** [comment]
Gotcha, thought you both were trying to make it look less huge.

**Comment by RoboMWM** [comment]
I can revert to this, but it makes no sense to me why some stuff would work (buttons) and some other stuff wouldn't (this header image). Probably better to test before pulling another change. If you'd like, I think you can enable github pages for your forked repo and set it to this branch to test changes. It'll show up under a github.io URL.

**Pull request closed without merging**
