### PR TITLE
optimized getClaim function

### PR DESCRIPTION
**Pull request by casperwtf**
HashMaps let us find the claim via the unique number with O(1) lookup time.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Thoughts on https://github.com/GriefPrevention/GriefPrevention/issues/2363 ?

**Comment by casperwtf** [comment]
Well I made this because GPFlags (a plugin using this method) was taking 20% of my server tick, I think you cant remove the API entirely but it should definitely move to a Map. This optimization reduced my usage from 20% to 0.3%. @RoboMWM

**Comment by Jikoo** [comment]
I was under the impression GPFlags had done a relatively significant rewrite of handling not too long ago to remove dependence on this method.

Overall I have no objections to this. The extra memory it adds is a drop in the bucket compared to the way GP stores claim lookups. It is likely something we should revisit with v18, but having a bandaid in now/applied to legacy would be good. Definitely a pain point for addons.

**Comment by casperwtf** [comment]
It might have been updated to remove this dependance but I am on a legacy version of the plugin, I backported this optimization to fit my version but theres no reason that people moving forward shouldn't have it as-well.

**Comment by akdukaan** [comment]
> It might have been updated to remove this dependance but I am on a legacy version of the plugin, I backported this optimization to fit my version but theres no reason that people moving forward shouldn't have it as-well.

Hi, GPFlags dev here. What version is your server? If it's 1.16 or newer, a lot of the newer versions of GPFlags have had lots of fixes with the older ones in that range. And if there are still remaining incompatibilties, I'd love to know about them so I can fix them.

**Comment by casperwtf** [comment]
Server Version 1.20.4
GP: 16.18.2
GPFlags: 5.12.11

**Comment by RoboMWM** [comment]
> Overall I have no objections to this. The extra memory it adds is a drop in the bucket compared to the way GP stores claim lookups. It is likely something we should revisit with v18, but having a bandaid in now/applied to legacy would be good. Definitely a pain point for addons.

yea, probably can do this. I'm thinking of annotating as `@Deprecated` tho? Since I still don't see any use case for this method..?

**Comment by casperwtf** [comment]
The use-case for the method would be accessing claims directly based off their ID via the api, that is very important functionality in my opinion.

**Comment by Jikoo** [comment]
> I'm thinking of annotating as `@Deprecated` tho? Since I still don't see any use case for this method..?

While I think the vast majority of cases have no reason not to use location-based lookups (most uses of ID lookups are design choices rather than necessity), claim ID is the unique identifier for claims in the datastore, so searching by it should be possible and performant. Location is not, and requires much more work to maintain because claims may be resized and moved.

The only example that really springs to mind is data validation: If I offer a feature with external data storage and I want to verify that my data is attached to a real claim (like how GP ensures claims belong to real worlds), should I create a list of all IDs I have, iterate over every claim in GP and remove matches, then drop any IDs that I don't find at the end? It makes way more sense to go through all of my data and ask GP "Hey, do you still have this claim?" and drop if relevant than to jump through several hoops to avoid using claim IDs for lookups.

I'm sure there are better examples of use cases (this would be more of a one-time hit on startup), but I'm not exactly known for my creation of new project concepts.

> The use-case for the method would be accessing claims directly based off their ID via the api, that is very important functionality in my opinion.

That's not really a use case, that's a description of what the method does. A use case is more along the lines of a practical example of something that can be accomplished with the method.

In the case of GPFlags, lookups can be done by location for the most part, BigScary just chose not to in the original design to slightly reduce some duplicate logic in a roundabout way. The data validation example I gave would be relevant to GPFlags, because while it is possible to accomplish without the method, having the method removes the need for at least one if not two loops to verify data is attached to a real claim.

**Comment by QarthO** [comment]
Can agree that it shouldn't be deprecated.

A couple use cases I have off the top of my head are to look up via ID is 
- if you want to chunk load specific claims on server startup. Ideally the addon would store claim ID's then on boot look up these IDs and get their location to load them.
- Custom datastore. All though not possible with the current API, I know there's been discussion about improving or adding the ability to use custom datastores (ie. SQL based). Having claim ID lookups will be a necessity.

**Comment by RoboMWM** [comment]
As an fyi, if you want this to be included in the legacy (v16) releases as well, you'll need to PR to that branch.

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
