### PR TITLE
Use BB logic for tree/portal creation

### LINKED ISSUE #1432: 1.17 Moss block can be used to change blocks in claim
### What happened:
Using bonemeal on a moss block at the edge of a claim replaces stone & grass-like blocks within the claim

### What was expected:
No blocks within the claim are replaced

### Steps to reproduce:
1. Create an admin claim on grass and/or stone (or get another player to create a claim)
2. Deop yourself (or make sure you don't have trust in the other player's claim)
3. Place a moss block just outside of the claim
4. Use bonemeal on the moss block
5. Observe grass/stone is replaced by moss blocks within the claim

### Server and GriefPrevention version:
Paste of `/version`: This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)
Paste of `/version GriefPrevention`: GriefPrevention version 16.17.1-2b69191

### Stack trace/error or server log

```
None

```

### GriefPrevention config.yml

Default config 
```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Disabled
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
Brand new blank server, no other plugins

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

### PR DESCRIPTION
**Pull request by Jikoo**
* Extract bounding box -> chunk claims logic to datastore
  * Reduces duplicate code for similar method
* Extract intersection logic to helper methods
* Apply intersection logic to tree growth
* Apply intersection logic to nether portal creation
* ~~Handle soul fire the same way as fire~~
  * Soul fire does not spread and has different infiniburn blocks. We can just ignore it.
* Fix fires adjacent to claims burning away blocks inside claim border
* Prevent sculk growing into claims
* Prevent moss growing if it will grow into claims the bonemeal user does not have access to
  * If player is not available, follows same rules as dispensers: if claim owners match, action is allowed.
  * Uses extracted intersection logic from pistons

This is a behavioral change.
Old: GP allows tree to grow but removes all elements conflicting with claim
New: GP determines that there is not enough room for the tree to grow, prevents the growth, and breaks the sapling

Closes #1432

### CODE REVIEW

**Comment by Jikoo** [comment]
This is a draft because I've been pretty busy and have not tested this well. I can verify that the original commits didn't cause issues, but I cherry-picked them blindly and don't have time to do more today.

I apologize for throwing so many changes in at once, ideally I should have extracted the piston logic in a completely separate commit on top of separate PRs for each of the existing commits.

If anyone's willing, a list of things that need confirmation:
* [x] Pistons still work as expected in `EVERYWHERE_SIMPLE` mode
* [x] Visualizing nearby claims works
* [x] Tree growth
  * [x] Growth is blocked only when relevant
  * [x] Sapling is broken
* [ ]  Portal placement
  * Uses same logic as trees, probably doesn't need testing if trees pass, particularly since it's kind of a pain to set up for
* [x] Fire spread
  * [x] Global rules
  * [x] Spread into claims
  * [x] Extinguishing spread source if spread is blocked and not on an infiniburn material
* [x] Sculk spread
* [x] Moss bonemealing 

CC @lerokko, build should be available via GP's AppVeyor if you have the time to spare. If not, I'll try to get some testing done tomorrow.

**Comment by Jikoo** [comment]
I still have not tested portal placement, but since it uses the same logic as trees, I can't see it being problematic.

Not happy about the scope of this PR, but sculk and moss being two different events, one of which previously only handled fire, made this a lot more of a mess.

I do still have some concerns about fire handling. Namely, GP adds in weird behavior where non-infinite fires become infinite inside claims with fire spread disabled. To make this worse, for whatever reason fire just doesn't seem to spread on Paper, which means you see this behavior even with gamerule `doFireSpread` (is that even a vanilla gamerule? May be Spigot) true. I can't find a config for it - I upped the fire tickrate, checked gamerules, upped random tickrate, nothing. Swapping to Spigot immediately started fire spreading again.
Personally, I think GP should extinguish those fires so as to prevent useless repeated burn attempts (especially since that's what it does when the fire actually tries to spread), but I know some users expect the behavior. Either way, that's even farther outside of the scope of this PR than a lot of the stuff that's already in it.

**Comment by RoboMWM** [comment]
> Personally, I think GP should extinguish those fires so as to prevent useless repeated burn attempts

Yes, this is something I want - I've realized that players aren't aware that their own structures for fireplaces aren't safe, but because they've used GP, they never realized this was the case until their claim expired or such.

**Comment by RoboMWM** [comment]
Thoughts on including this in beta release? Though I may postpone this to another beta release, given the amount of changes I already wish to be tested.

**Comment by Jikoo** [comment]
I think the current beta has enough internal changes that this waiting for the next beta iteration is good, yeah.

**Review by RoboMWM — DISMISSED** [review]
I'm ok with behavior change

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
