### PR TITLE
Ignore trash blocks when auto-extending

### LINKED ISSUE #2046: Claims.ExtendIntoGroundDistance is ignored
### Observed Behavior

Value set in Claims.ExtendIntoGroundDistance is being ignored
New claim's depth is going all the way to the value set in MaximumDepth

### Expected Behavior

As described in the manual, claim's lowest Y coordinate should be 'lowest point - Claims.ExtendIntoGroundDistance' and go down when player digs and builds lower.

### Reproduction steps

1. Set Claims.ExtendIntoGroundDistance = 5 ( default ) in config
2. Set MaximumDepth to some 'value1'
3. Clean server start, create new claim
4. Examine blocks below the claim and see that claim's lowest boundary is defined by variable MaximumDepth ( Y coord = value1 )
5. Set MaximumDepth to some 'value2' and repeat experiment (set new claim) -- now the lowest claim's boundary is defined by 'value2'

Examining was done "with a stick" as well as "try breaking a block" -
claim is clearly/correctly reporting itself as well as can't break block unless using '/ignoreclaims'.

### Stack trace or error log

```shell
N/A - no errors or stacks generated
```

### Server version

```shell
[15:46:25 INFO]: This server is running Paper version git-Paper-516 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f7717c3)
```

### GriefPrevention version

```shell
> version GriefPrevention
[15:47:12 INFO]: GriefPrevention version 16.18.1
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    staging: -1
  Claims:
    Mode:
      world: Survival
      staging: Survival
      world_the_end: Disabled
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      staging: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 10.0
    ClaimBlocksSellValue: 10.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: jdbc:mysql://mdba-1.srv.home:3306/minecraft_cubedpants_gp
    UserName: mcr_cubed_gp
    Password: nKJ9yHTCMdXL4mgkiSqJQUrSe
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
> plugins
[15:48:44 INFO]: Server Plugins (13):
[15:48:44 INFO]: Bukkit Plugins:
[15:48:44 INFO]:  - ChestShop, Essentials, EssentialsChat, EssentialsSpawn, Graves, GriefPrevention, GSit, LuckPerms, Multiverse-Core, Multiverse-Inventories
[15:48:44 INFO]:  TAB, Vault, WorldEdit
>
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

### PR DESCRIPTION
**Pull request by Jikoo**
* Update material/biome definitions for 1.20 barring snapshot stuff
* Expose trash block list
* Remove trash blocks when assembling auto-extension materials
  * Should ideally prevent most cases of basic player-created mineshafts being considered part of an overhead claim
 
Food for thought: also ignore wooden planks? I don't think they should be trash blocks because they're baby's first house material, but they're also pretty commonly used when exploring a ravine or whatever because they're the last stuff you've got left.

I'm considering this to be enough to close #2046 because we have #2199 also tracking the need for configurability here.

Also I promise this is the last PR I'll make until you deal with the backlog, I've had some time off and I've been having a heck of a time just doing hobby things.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Ya, the naturerestore logic I know is part of auto-extend. Not sure how I want to deal with this. I know we can expose a list of blocks (which IMO, blegh), but I rather not have it depend on a list of materials that can change with new biomes and name changes... my initial thought was just to extend it down as the claim owner/trustees started performing actions below the claim as an easy way to extend.

**Comment by RoboMWM** [comment]
Oh, misread, it's removing it from the list of blocks to check, ok.

Still blegh about exposing the list anyways, would like to make that a separate plugin/addon altogether. Maybe GP I guess could also fire an event or something for considering auto-extend? Or just have addons manually extend the claim or something? Hmm...

**Comment by QarthO** [comment]
Why are we checking for type of blocks anyways? Just seems simpler to check if an owner places any block at all below their claim to auto extend.

The auto-extending task is something that is extremely confusing for players. I don't like the idea of having some hardcoded and arbitrary material list that needs to be updated whenever minecraft updates, or not work at all in any custom terrain generation. Just seems best to remove the block type check, and just have it as simple as possible, (and makes it easier to maintain)

**Comment by Jikoo** [comment]
>  I rather not have it depend on a list of materials that can change with new biomes and name changes

I talked a little about my ideal future state for this in #2199. I'd like the actual auto-extension list to be configurable and default only to blocks that are actually high value. I agree that I don't see a need for biome-based separation, because imo all per-biome blocks are trash that don't need to be encompassed anyway. This is a bandaid for it pretty much always slapping down to bedrock immediately because gravel is common as heck on new generation, not a proper step towards future state.

> Why are we checking for type of blocks anyways? Just seems simpler to check if an owner places any block at all below their claim to auto extend.
> 
> The auto-extending task is something that is extremely confusing for players. I don't like the idea of having some hardcoded and arbitrary material list that needs to be updated whenever minecraft updates, or not work at all in any custom terrain generation. Just seems best to remove the block type check, and just have it as simple as possible, (and makes it easier to maintain)

This auto-extension is confusingly named. It only runs when a claim is created (maybe also resized? I forget) and is designed to prevent users from accidentally not claiming valuables due to claim depth. Delete your claim over your turbobasement megabase, create the claim again at the surface, whoopsie, entire underground is unclaimed. Hope you didn't want that stuff, cause Joe Smith can mine right in and take it now.

The normal auto-extension extends claims when someone with build trust places a block beneath its limits just as you're describing.

**Comment by RoboMWM** [comment]
Mmmm I see the case for scanning for player-placed blocks on claim creation. Maybe instead of a list we can hand that off to an ai xd.

Idk if there's a better option than having to deal with a list of Materials... would like to avoid having to do that scan, but I guess it's necessary for 2D-defined claims with a semi-3D protection (lower y depth)...

**Comment by Jikoo** [comment]
I think in terms of a basic list I'd actually say searching entities/tile entities would be enough that I wouldn't be worried. What are the odds that someone lines the bottom of their base with diamond blocks and doesn't build anything else there? Extending to cover item frames, armor stands, lootable containers that do not have loot tables, and non-lootable containers should be sufficient for 99% of builds and doesn't require us to check every block. It also would do way better at not automatically encompassing vanilla's abandoned mineshafts and stuff, the things miners would love to explore under a claim. We could flat out just leave more specific extension to an addon.

**Review by RoboMWM — APPROVED** [review]
Not sure why I thought you meant you were putting the list in the configuration with "expose list", I see that's not happening and you're just exposing it programmatically.

**Pull request merged**
