### PR TITLE
Feature: Protect passive pillagers from being killed in claims

### PR DESCRIPTION
**Pull request by FrankHeijden**
Pillagers are passive when they don't have a bow in their hand (see: https://minecraft.gamepedia.com/Pillager#Behavior), this PR aims to add protection for passive pillagers when protecting creatures is enabled in the config.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Unsure about this as it still affects other entities despite being unable to harm.

**Comment by FrankHeijden** [comment]
> Unsure about this as it still affects other entities despite being unable to harm.

I am not quite sure how that's related to players being able to kill this passive entity?

**Comment by RoboMWM** [comment]
Because it still causes negative effects to other entities.

I guess it's not that big of a deal since it's no threat to the player, but still... eh. GP was meant to protect animals for obvious farming reasons, makes me wonder if "protect all passive mobs" is a bit of feature creep.

**Comment by Jikoo** [comment]
In addition to Robo's concerns (namely, scaring villagers/being killed by golems), I think this should be in an addon because it's a Java-edition-specific inconsistency and [has been reported as a bug](https://bugs.mojang.com/browse/MC-163960).

**Comment by FrankHeijden** [comment]
> In addition to Robo's concerns (namely, scaring villagers/being killed by golems), I think this should be in an addon because it's a Java-edition-specific inconsistency and [has been reported as a bug](https://bugs.mojang.com/browse/MC-163960).

This is the intention of protecting the pillager, it is used in iron-farms designs. I really dislike to put this into an addon, mainly, because there is little API for addons. New features in gp aren’t too bad ;). Don’t really think the bug tracker is a good reference, since the bug has been open since last year, and many people vouch for this bug to stay in the game. When it gets resolved we can easily remove it again from GP.

**Comment by Jikoo** [comment]
> This is the intention of protecting the pillager, it is used in iron-farms designs.

I get that it has cool creative potential.

> I really dislike to put this into an addon, mainly, because there is little API for addons.

The API is 100% sufficient in this case. GP ignores damage to pillagers because they're monsters.

Here's your addon:
```Java
@EventHandler(ignoreCancelled = true)
public void featureProtectUnarmedPillager(EntityDamageByEntityEvent event) {
    if (event.getEntityType() != EntityType.PILLAGER) return;

    Pillager pillager = (Pillager) subEvent.getEntity();
    EntityEquipment equipment = pillager.getEquipment();

    if (equipment != null && (equipment.getItemInMainHand().getType() != Material.AIR || equipment.getItemInOffHand().getType() != Material.AIR)) return;

    Entity damager = event.getDamager();
    Player attacker;
    if (damager instanceof Player) {
        attacker = (Player) damager;
    } else if (damager instanceof Projectile) {
        ProjectileSource shooter = ((Projectile) damager).getShooter();
        if (shooter instanceof Player) {
            attacker = (Player) shooter;
        }
    }

    Claim cachedClaim = null;
    PlayerData playerData = null;
    if (attacker != null) {
        playerData = GriefPrevention.instance.dataStore.getPlayerData(attacker.getUniqueId());
        cachedClaim = playerData.lastClaim;
    }

    Claim claim = this.dataStore.getClaimAt(event.getEntity().getLocation(), false, cachedClaim);

    if (claim == null) return;

    if (attacker == null) {
        event.setCancelled(true);
        return;
    }

    String failureReason = claim.allowBuild(attacker, Material.AIR);

    if (failureReason == null) return;

    event.setCancelled(true);
    GriefPrevention.sendMessage(attacker, TextMode.Err, failureReason);
    playerData.lastClaim = claim;
}
```

If the API truly was insufficient, you should probably either open an issue describing the problem or PR a fix.

> New features in gp aren’t too bad ;). Don’t really think the bug tracker is a good reference, since the bug has been open since last year, and many people vouch for this bug to stay in the game. When it gets resolved we can easily remove it again from GP.

It's additional work that may be required at any point in the future. What are the odds that we remember? Consider how much technical debt GP currently has and how many missed cases exist every single update. The fact that the issue is open means that Mojang is willing to take it on at some point in the future. Age isn't a good indicator of willingness to fix issues.

Re: new core features in general: Every new addition should be designed with the future vision for v20 in mind. Even creative claims mode is (tentatively) planned to be spun off into an addon to allow finer-grained tuning of parameters. Features oriented towards powerusers probably shouldn't be added to the core plugin because they increase code complexity more than they increase usability for the average player.

**Comment by RoboMWM** [comment]
Ah I see, this mob isn't normal, it's only after its crossbow durability is consumed. What would stop a player from giving it another crossbow, and thus making it suddenly hostile again?

**Comment by FrankHeijden** [comment]
> Ah I see, this mob isn't normal, it's only after its crossbow durability is consumed. What would stop a player from giving it another crossbow, and thus making it suddenly hostile again?

The pillager won’t pickup any weapons; it is completely passive / tamed.

**Pull request closed without merging**
