### PR TITLE
Remove unnecessary fire handling

### PR DESCRIPTION
**Pull request by Jikoo**
Fire has a real hit box now, clients hit it directly instead of the server raytracing swings at the block beneath it.

### CODE REVIEW

**Comment by Jikoo** [comment]
Not sure why this is a line ending difference, locally both are CRLF. Wonder if my git normalized the line endings or something, thought I had disabled that.

**Comment by Jikoo** [comment]
Well, tried remaking the commit after [adding a .gitattributes](3caa68bc5d7914138ff9921a156879f7a29ee2ea), and I still ended up with a massive whitespace diff. After some searching, all the CRLF support settings just make the files CRLF when checked out but still commits them as LF. https://stackoverflow.com/questions/51229226/how-to-force-git-commit-with-crlf We can enforce LF, we cannot enforce CRLF. Setting to auto still causes trouble with `core.autocrlf`, so asking for CRLF endings in git is a huge PITA because committers actually cannot touch certain global settings.

**Comment by RoboMWM** [comment]
Hmm, I could give it a go I guess as well. Not sure if uploading a patch file will show the smaller diff?

I could futz around with git and see if I can take in your patch file directly or generate a patch myself, or just do the change and amend you as the author, etc.

**Comment by Jikoo** [comment]
I think I'm just gonna have to locally add a .gitattributes that claims .java files are binaries so my git install stops doing this, only thought of that option tonight. If that doesn't work, I dunno, might have to install the GitHub client or something and hope that they didn't extend their opinionated git practices to that. My git install doesn't actually have `core.autocrlf` set, so I'm not sure why it's stripping this file, especially since it doesn't (always) strip other files.

Alternate solution is to beg you to add a .gitattributes and move to LF line endings in the repo, CRLF when checking out.

**Comment by RoboMWM** [comment]
Ya, forgot to add, that I don't mind fixing these, but ideally would like to fix these line endings either myself, or with a PR that doesn't make any changes. I suppose I could test with this file, and then you can resolve conflicts after.

**Comment by Jikoo** [comment]
Hmm, still huge. I'll mess around with it tomorrow and try the last few ideas. Frustrating, but I guess it's probably been ongoing randomly for a while and I've just assumed things were okay on my end because I hadn't made any changes.

**Comment by Jikoo** [comment]
I tried a couple iterations before making #2269 and wasn't able to figure out how to force my git install to stop renormalizing the line endings. Super weird and frustrating because one of the merge conflicts is me touching the same file from the same system with the same settings with no trouble, but oh well, ideally that's a more maintainable solution anyway.

**Comment by RoboMWM** [comment]
Hmm, wonder when they changed this. Is extinguishing fire a BlockBreakEvent now?

**Review by RoboMWM — APPROVED** [review]

**Comment by Jikoo** [comment]
It is, yeah. I believe it changed with soul fire's addition, but could be wrong.

**Pull request merged**
