### PR TITLE
Protect rooted_dirt

### LINKED ISSUE #1535: 1.17 dupe hanging_roots with rooted_dirt
### What happened:
With an hoe enchanted with silk touch inside a zone claimed that you haven't the trust if you try to remove the hanging roots from the rooted dirt it gives you illimitates hanging roots

### What was expected:
To not give you the hanging_roots

### Steps to reproduce:
1. Stay inside a claim that you haven't the access
2. Grab an hoe enchanted with silk touch
3. try to right-click a rooted dirt
4. You have illimitate hanging_roots
video of the bug (https://www.youtube.com/watch?v=gJo6gsv5FIs)

### Server and GriefPrevention version:
Paste of /version: 
This server is running Airplane version git-Airplane-"ec7d3d0" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) 

Paste of /ver griefprevention:
GriefPrevention version ${git.commit.id.describe}
(Latest commit e8c5b37)

### Stack trace/error or server log

```
No error occurred in console
```

### GriefPrevention config.yml

```yml

https://drive.google.com/file/d/15qWdDsfRWafjyIMyeDDHVlbeRkrjxJUG/view?usp=drivesdk

```

### Plugin list (if applicable):

Plugins (49): AdvancedDevelopmentLibrary, AngelChest, BetterJails, BetterRTP, BossShopPro, BungeeGuard, BuycraftX, ChatReaction, ChatSentinel, ChestShop, CoreProtect, CrateReloaded, DeluxeChat, Elevator, EntityDetection, Essentials, EssentialsSpawn, ExperienceCore, EZColors, FarmLimiter, GriefPrevention, HolographicDisplays, Images, LuckPerms, MeteoritesPro, MineableSpawners, Minepacks, MoneyFromMobs, NametagEdit, NerfPhantoms, OpenInv, PL-Hide-Pro, PlaceholderAPI, PlugMan, ProtocolLib, Rankup, ReviveMe, SkinsRestorer, SuperbVote, SuperVanish, TitleManager, TradeSystem, TreeAssist, UltimateCatcher, Vault, Votifier, Voting, WorldEdit, WorldGuard

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

### PR DESCRIPTION
**Pull request by akdukaan**
Closes https://github.com/TechFortress/GriefPrevention/issues/1535
The first commit adds rooted_dirt to the non-right-clickable blocks.
The second and third commit changes the order so that all items in there are in alphabetical order and tag checks are last.

### CODE REVIEW

**Comment by LogGits** [comment]
Confirmed this is a working fix, can you also please move the tag checks in that statement to the end.
Great work, lgtm 👍

**Comment by RoboMWM** [comment]
Did you re-sort the statements or something?

**Comment by RoboMWM** [comment]
Oh I see your description. Needless change but whatever.

**Comment by bigpresh** [comment]
Looks sane to me. :+1:

**Comment by tommasobenatti** [comment]
BUMP

**Comment by RoboMWM** [comment]
I know I need not respond, but I wanna, and I wanna say, needless bump is needless bump.

A useful bump is If you can verify it working as intended (preferably with details). Then I'd be more inclined to get it pulled.

Especially when items are resorted, to ensure that nothing was missed on accident.

**Review by RoboMWM — APPROVED** [review]
If things look good @bigpresh feel free to add an approving review so I can see that you approve at a glance. c:

**Pull request merged**
